// packages/vue/src/components/TextField/TextField.vue
<script lang="ts">
import type { FieldAccentColor, FieldSize } from "../Field/Field.vue";

export type TextFieldSize = FieldSize;
export type TextFieldColor = FieldAccentColor;

/**
 * Props follow MUI's TextField API (https://mui.com/material-ui/api/text-field/)
 * as closely as this design allows, mirroring `@okkly/react`'s `<TextField>`
 * name-for-name. Deliberate differences, because Vue has no `ReactNode`:
 * `label`, `helperText`, `startAdornment` and `endAdornment` arrive as the
 * `label`, `helper-text`, `start-adornment` and `end-adornment` slots. The
 * controlled `value` becomes `defineModel`, so consumers can `v-model` it;
 * every other native input attribute (`type`, `placeholder`, `name`,
 * `maxlength`, `@input`, `@change`…) falls through to the rendered `<input>`
 * on its own — `class` is the one exception, which lands on the outer field
 * wrapper instead, matching React's `className`.
 * Deliberate gaps: no `variant` (the design has one visual treatment, not
 * filled/outlined/standard), no `multiline`/`rows`/`select` (not in this
 * component's Figma spec — would be new, undesigned surface).
 */
export interface TextFieldProps {
  /**
   * Visually hides the label (still present for assistive tech).
   *
   * @default false
   */
  hideLabel?: boolean;
  /**
   * Field height & text.
   *
   * @default "medium"
   */
  size?: TextFieldSize;
  /**
   * Tints the focus ring/glow. One of the design system's accent colors —
   * `dante` is a rare, deliberate accent moment; the rest are for matching
   * a field to surrounding brand/section color.
   *
   * @default "primary"
   */
  color?: TextFieldColor;
  /**
   * Marks invalid + red border.
   *
   * @default false
   */
  error?: boolean;
  /**
   * If `true`, the field takes the full width of its container.
   *
   * @default false
   */
  fullWidth?: boolean;
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   */
  required?: boolean;
  /**
   * Disables the input.
   *
   * @default false
   */
  disabled?: boolean;
  /**
   * Id of the rendered `<input>`; also what the label's `for` and the helper
   * text's id derive from. Auto-generated with `useId()` when omitted.
   *
   * @default undefined
   */
  id?: string;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useId } from "vue";
import "@okkly/design-system/components/TextField/TextField.scss";
import Field, { getFieldIds } from "../Field/Field.vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<TextFieldProps>(), {
  hideLabel: false,
  size: "medium",
  color: "primary",
  error: false,
  fullWidth: false,
  required: false,
  disabled: false,
  id: undefined,
});

const slots = defineSlots<{
  /** Field label. */
  label?: () => unknown;
  /** Text below field. */
  "helper-text"?: () => unknown;
  /** Content rendered inside the border, before the input. */
  "start-adornment"?: () => unknown;
  /** Content rendered inside the border, after the input. */
  "end-adornment"?: () => unknown;
}>();

const model = defineModel<string>();

const attrs = useAttrs();
const inputAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});

const generatedId = useId();
const inputId = computed(() => props.id ?? generatedId);
const describedBy = computed(() => {
  const { helperId } = getFieldIds(inputId.value, false, !!slots["helper-text"]);
  return (
    [helperId, attrs["aria-describedby"] as string | undefined].filter(Boolean).join(" ") ||
    undefined
  );
});
</script>

<template>
  <Field
    block="okkly-text-field"
    :id="inputId"
    :class="attrs.class"
    :hide-label="hideLabel"
    :required="required"
    :size="size"
    :color="color"
    :error="error"
    :disabled="disabled"
    :full-width="fullWidth"
  >
    <template v-if="slots.label" #label><slot name="label" /></template>
    <template v-if="slots['helper-text']" #helper-text><slot name="helper-text" /></template>
    <template v-if="slots['start-adornment']" #start-adornment
      ><slot name="start-adornment"
    /></template>
    <template v-if="slots['end-adornment']" #end-adornment><slot name="end-adornment" /></template>

    <input
      :id="inputId"
      v-model="model"
      v-bind="inputAttrs"
      class="okkly-text-field__input"
      :disabled="disabled"
      :required="required"
      :aria-invalid="error || undefined"
      :aria-describedby="describedBy"
    />
  </Field>
</template>

// packages/react/src/components/TextField/TextField.tsx
"use client";

import { forwardRef, useId, type InputHTMLAttributes, type ReactNode } from "react";
import "@okkly/design-system/components/TextField/TextField.scss";
import { Field, getFieldIds, type FieldAccentColor, type FieldSize } from "../Field/Field";

export type TextFieldSize = FieldSize;
export type TextFieldColor = FieldAccentColor;

/**
 * Props follow MUI's TextField API (https://mui.com/material-ui/api/text-field/)
 * as closely as this design allows: `label`/`size`/`error`/`helperText`/
 * `disabled`/`fullWidth`/`color`/`value`/`onChange`/`required` all match
 * name-for-name, and `startAdornment`/`endAdornment` are lifted to the top
 * level rather than living under `InputProps`.
 * Deliberate gaps: no `sx`/`classes`/`slots`/`slotProps` (no CSS-in-JS system
 * here), no `variant` (the design has one visual treatment, not
 * filled/outlined/standard), no `multiline`/`rows`/`select`/`margin` (not in
 * this component's Figma spec — would be new, undesigned surface).
 */
export interface TextFieldProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  "size" | "color"
> {
  /**
   * Field label.
   *
   * @default undefined
   * @type {ReactNode}
   */
  label?: ReactNode;
  /**
   * Visually hides the label (still present for assistive tech).
   *
   * @default false
   * @type {boolean}
   */
  hideLabel?: boolean;
  /**
   * Field height & text.
   *
   * @default "medium"
   * @type {TextFieldSize}
   */
  size?: TextFieldSize;
  /**
   * Tints the focus ring/glow. One of the design system's accent colors —
   * `dante` is a rare, deliberate accent moment; the rest are for matching
   * a field to surrounding brand/section color.
   *
   * @default "primary"
   * @type {TextFieldColor}
   */
  color?: TextFieldColor;
  /**
   * Marks invalid + red border.
   *
   * @default false
   * @type {boolean}
   */
  error?: boolean;
  /**
   * Text below field.
   *
   * @default undefined
   * @type {ReactNode}
   */
  helperText?: ReactNode;
  /**
   * If `true`, the field takes the full width of its container.
   *
   * @default false
   * @type {boolean}
   */
  fullWidth?: boolean;
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   * @type {boolean}
   */
  required?: boolean;
  /**
   * Content rendered inside the border, before the input.
   *
   * @default undefined
   * @type {ReactNode}
   */
  startAdornment?: ReactNode;
  /**
   * Content rendered inside the border, after the input.
   *
   * @default undefined
   * @type {ReactNode}
   */
  endAdornment?: ReactNode;
}

export const TextField = forwardRef<HTMLInputElement, TextFieldProps>(function TextField(
  {
    label,
    hideLabel = false,
    size = "medium",
    color = "primary",
    error = false,
    helperText,
    fullWidth = false,
    disabled = false,
    required = false,
    startAdornment,
    endAdornment,
    className,
    id,
    "aria-describedby": ariaDescribedBy,
    ...rest
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const { helperId } = getFieldIds(inputId, Boolean(label), Boolean(helperText));

  return (
    <Field
      block="okkly-text-field"
      id={inputId}
      label={label}
      hideLabel={hideLabel}
      required={required}
      size={size}
      color={color}
      error={error}
      helperText={helperText}
      disabled={disabled}
      fullWidth={fullWidth}
      startAdornment={startAdornment}
      endAdornment={endAdornment}
      className={className}
    >
      <input
        ref={ref}
        id={inputId}
        className="okkly-text-field__input"
        disabled={disabled}
        required={required}
        aria-invalid={error || undefined}
        aria-describedby={[helperId, ariaDescribedBy].filter(Boolean).join(" ") || undefined}
        {...rest}
      />
    </Field>
  );
});
