// packages/react/src/components/TextArea/TextArea.tsx
"use client";

import {
  forwardRef,
  useCallback,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type ChangeEvent,
} from "react";
import "@okkly/design-system/components/TextArea/TextArea.scss";
import type { TextAreaProps } from "./TextArea.types";

export const TextArea = forwardRef<HTMLTextAreaElement, TextAreaProps>(function TextArea(
  {
    label,
    hideLabel = false,
    size = "medium",
    color = "primary",
    error = false,
    helperText,
    fullWidth = false,
    disabled = false,
    rows = 3,
    maxRows,
    autosize = false,
    maxLength,
    resize = "vertical",
    required = false,
    className,
    id,
    value,
    defaultValue,
    onChange,
    "aria-describedby": ariaDescribedBy,
    ...rest
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const helperId = helperText ? `${inputId}-helper` : undefined;
  const counterId = maxLength != null ? `${inputId}-counter` : undefined;

  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const [uncontrolledValue, setUncontrolledValue] = useState(() =>
    defaultValue != null ? String(defaultValue) : "",
  );

  const isControlled = value !== undefined;
  const currentValue = isControlled ? String(value) : uncontrolledValue;
  const charCount = currentValue.length;

  const setTextareaRef = useCallback(
    (node: HTMLTextAreaElement | null) => {
      textareaRef.current = node;
      if (typeof ref === "function") {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    },
    [ref],
  );

  const syncHeight = useCallback(() => {
    const el = textareaRef.current;
    if (!el || !autosize) {
      return;
    }

    el.style.height = "auto";

    const styles = getComputedStyle(el);
    const lineHeight = Number.parseFloat(styles.lineHeight);
    const paddingBlock =
      Number.parseFloat(styles.paddingTop) + Number.parseFloat(styles.paddingBottom);
    const borderBlock =
      Number.parseFloat(styles.borderTopWidth) + Number.parseFloat(styles.borderBottomWidth);

    const minHeight = rows * lineHeight + paddingBlock + borderBlock;
    let nextHeight = Math.max(el.scrollHeight, minHeight);

    if (maxRows != null) {
      const maxHeight = maxRows * lineHeight + paddingBlock + borderBlock;
      nextHeight = Math.min(nextHeight, maxHeight);
      el.style.overflowY = el.scrollHeight > maxHeight ? "auto" : "hidden";
    } else {
      el.style.overflowY = "hidden";
    }

    el.style.height = `${nextHeight}px`;
  }, [autosize, maxRows, rows]);

  useLayoutEffect(() => {
    syncHeight();
  }, [syncHeight, currentValue, rows, maxRows]);

  const handleChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    if (!isControlled) {
      setUncontrolledValue(event.target.value);
    }
    onChange?.(event);
  };

  const classes = [
    "okkly-component",
    "okkly-text-area",
    color !== "primary" && `okkly-text-area--color-${color}`,
    size !== "medium" && `okkly-text-area--${size}`,
    error && "okkly-text-area--error",
    fullWidth && "okkly-text-area--full-width",
    autosize && "okkly-text-area--autosize",
    resize !== "vertical" && `okkly-text-area--resize-${resize}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const describedBy = [helperId, counterId, ariaDescribedBy].filter(Boolean).join(" ") || undefined;
  const showFooter = Boolean(helperText || maxLength != null);

  return (
    <div className={classes}>
      {label && (
        <label
          htmlFor={inputId}
          className={`okkly-text-area__label${hideLabel ? " okkly-text-area__label--hidden" : ""}`}
        >
          {label}
          {required && (
            <span className="okkly-text-area__required" aria-hidden="true">
              *
            </span>
          )}
        </label>
      )}
      <div className="okkly-text-area__control">
        <textarea
          ref={setTextareaRef}
          id={inputId}
          className="okkly-text-area__textarea"
          rows={rows}
          disabled={disabled}
          required={required}
          value={isControlled ? value : undefined}
          defaultValue={isControlled ? undefined : defaultValue}
          maxLength={maxLength}
          aria-invalid={error || undefined}
          aria-describedby={describedBy}
          onChange={handleChange}
          {...rest}
        />
      </div>
      {showFooter && (
        <div className="okkly-text-area__footer">
          {helperText && (
            <span id={helperId} className="okkly-text-area__helper">
              {helperText}
            </span>
          )}
          {maxLength != null && (
            <span id={counterId} className="okkly-text-area__counter">
              {charCount} / {maxLength}
            </span>
          )}
        </div>
      )}
    </div>
  );
});

// packages/vue/src/components/TextArea/TextArea.vue
<script setup lang="ts">
import { computed, useAttrs, useId, useTemplateRef, watch } from "vue";
import "@okkly/design-system/components/TextArea/TextArea.scss";
import type { TextAreaProps } from "./TextArea.types";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<TextAreaProps>(), {
  hideLabel: false,
  size: "medium",
  color: "primary",
  error: false,
  fullWidth: false,
  disabled: false,
  rows: 3,
  maxRows: undefined,
  autosize: false,
  maxLength: undefined,
  resize: "vertical",
  required: false,
  id: undefined,
});

const slots = defineSlots<{
  /** Field label. */
  label?: () => unknown;
  /** Text below the field (footer row, left). */
  "helper-text"?: () => unknown;
}>();

const model = defineModel<string>();

const attrs = useAttrs();
const textareaAttrs = computed(() => {
  const { class: _class, "aria-describedby": _describedBy, ...rest } = attrs;
  return rest;
});

const generatedId = useId();
const inputId = computed(() => props.id ?? generatedId);
const helperId = computed(() => (slots["helper-text"] ? `${inputId.value}-helper` : undefined));
const counterId = computed(() =>
  props.maxLength != null ? `${inputId.value}-counter` : undefined,
);
const describedBy = computed(
  () =>
    [helperId.value, counterId.value, attrs["aria-describedby"] as string | undefined]
      .filter(Boolean)
      .join(" ") || undefined,
);
const showFooter = computed(() => !!slots["helper-text"] || props.maxLength != null);
const charCount = computed(() => model.value?.length ?? 0);

const textareaRef = useTemplateRef<HTMLTextAreaElement>("textarea");

function syncHeight() {
  const el = textareaRef.value;
  if (!el || !props.autosize) {
    return;
  }

  el.style.height = "auto";

  const styles = getComputedStyle(el);
  const lineHeight = Number.parseFloat(styles.lineHeight);
  const paddingBlock =
    Number.parseFloat(styles.paddingTop) + Number.parseFloat(styles.paddingBottom);
  const borderBlock =
    Number.parseFloat(styles.borderTopWidth) + Number.parseFloat(styles.borderBottomWidth);

  const minHeight = props.rows * lineHeight + paddingBlock + borderBlock;
  let nextHeight = Math.max(el.scrollHeight, minHeight);

  if (props.maxRows != null) {
    const maxHeight = props.maxRows * lineHeight + paddingBlock + borderBlock;
    nextHeight = Math.min(nextHeight, maxHeight);
    el.style.overflowY = el.scrollHeight > maxHeight ? "auto" : "hidden";
  } else {
    el.style.overflowY = "hidden";
  }

  el.style.height = `${nextHeight}px`;
}

watch([model, () => props.rows, () => props.maxRows, () => props.autosize], () => syncHeight(), {
  flush: "post",
  immediate: true,
});

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-text-area",
    props.color !== "primary" && `okkly-text-area--color-${props.color}`,
    props.size !== "medium" && `okkly-text-area--${props.size}`,
    props.error && "okkly-text-area--error",
    props.fullWidth && "okkly-text-area--full-width",
    props.autosize && "okkly-text-area--autosize",
    props.resize !== "vertical" && `okkly-text-area--resize-${props.resize}`,
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <div :class="[classes, attrs.class]">
    <label
      v-if="slots.label"
      :for="inputId"
      :class="['okkly-text-area__label', hideLabel && 'okkly-text-area__label--hidden']"
    >
      <slot name="label" />
      <span v-if="required" class="okkly-text-area__required" aria-hidden="true">*</span>
    </label>
    <div class="okkly-text-area__control">
      <textarea
        :id="inputId"
        ref="textarea"
        v-model="model"
        v-bind="textareaAttrs"
        class="okkly-text-area__textarea"
        :rows="rows"
        :disabled="disabled"
        :required="required"
        :maxlength="maxLength"
        :aria-invalid="error || undefined"
        :aria-describedby="describedBy"
      />
    </div>
    <div v-if="showFooter" class="okkly-text-area__footer">
      <span v-if="slots['helper-text']" :id="helperId" class="okkly-text-area__helper">
        <slot name="helper-text" />
      </span>
      <span v-if="maxLength != null" :id="counterId" class="okkly-text-area__counter">
        {{ charCount }} / {{ maxLength }}
      </span>
    </div>
  </div>
</template>
