// packages/react/src/components/Collapse/Collapse.tsx
"use client";

import { forwardRef, useRef, type CSSProperties } from "react";
import { Transition } from "react-transition-group";
import "@okkly/design-system/components/Collapse/Collapse.scss";

import { useForkRef } from "@okkly/react-hooks";
import {
  DURATION_STANDARD,
  getAutoHeightDuration,
  getTransitionProps,
  mergeClassNames,
  normalizedTransitionCallback,
  reflow,
} from "../../helpers";
import type { CollapseProps } from "./Collapse.types";

export const Collapse = forwardRef<HTMLDivElement, CollapseProps>(function Collapse(
  {
    addEndListener,
    appear = true,
    children,
    className,
    collapsedSize: collapsedSizeProp = "0px",
    easing,
    in: inProp = false,
    onEnter,
    onEntered,
    onEntering,
    onExit,
    onExited,
    onExiting,
    orientation = "vertical",
    style,
    timeout = DURATION_STANDARD,
    mountOnEnter,
    unmountOnExit,
    ...other
  },
  ref,
) {
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const autoTransitionDuration = useRef(0);
  const collapsedSize =
    typeof collapsedSizeProp === "number" ? `${collapsedSizeProp}px` : collapsedSizeProp;
  const isHorizontal = orientation === "horizontal";
  const size = isHorizontal ? "width" : "height";

  const nodeRef = useRef<HTMLDivElement | null>(null);
  const handleRef = useForkRef(ref, nodeRef);

  const getWrapperSize = () =>
    wrapperRef.current ? wrapperRef.current[isHorizontal ? "clientWidth" : "clientHeight"] : 0;

  const handleEnter = normalizedTransitionCallback(nodeRef, (node, isAppearing) => {
    if (wrapperRef.current && isHorizontal) {
      wrapperRef.current.style.position = "absolute";
    }
    node.style[size] = collapsedSize;
    onEnter?.(node, isAppearing ?? false);
  });

  const handleEntering = normalizedTransitionCallback(nodeRef, (node, isAppearing) => {
    const wrapperSize = getWrapperSize();

    if (wrapperRef.current && isHorizontal) {
      wrapperRef.current.style.position = "";
    }

    const { duration: transitionDuration, easing: transitionTimingFunction } = getTransitionProps(
      { style, timeout, easing },
      { mode: "enter" },
    );

    if (timeout === "auto") {
      const duration = getAutoHeightDuration(wrapperSize);
      node.style.transitionDuration = `${duration}ms`;
      autoTransitionDuration.current = duration;
    } else {
      node.style.transitionDuration =
        typeof transitionDuration === "string" ? transitionDuration : `${transitionDuration}ms`;
    }

    node.style[size] = `${wrapperSize}px`;
    if (transitionTimingFunction) {
      node.style.transitionTimingFunction = transitionTimingFunction;
    }

    onEntering?.(node, isAppearing ?? false);
  });

  const handleEntered = normalizedTransitionCallback(nodeRef, (node, isAppearing) => {
    node.style[size] = "auto";
    onEntered?.(node, isAppearing ?? false);
  });

  const handleExit = normalizedTransitionCallback(nodeRef, (node) => {
    // Lock current size in px before leaving `height/width: auto` (via --entered).
    node.style[size] = `${getWrapperSize()}px`;
    onExit?.(node);
  });

  const handleExited = normalizedTransitionCallback(nodeRef, onExited);

  const handleExiting = normalizedTransitionCallback(nodeRef, (node) => {
    // Ensure the browser commits the px size from onExit before animating down.
    reflow(node);

    const wrapperSize = getWrapperSize();
    const { duration: transitionDuration, easing: transitionTimingFunction } = getTransitionProps(
      { style, timeout, easing },
      { mode: "exit" },
    );

    if (timeout === "auto") {
      const duration = getAutoHeightDuration(wrapperSize);
      node.style.transitionDuration = `${duration}ms`;
      autoTransitionDuration.current = duration;
    } else {
      node.style.transitionDuration =
        typeof transitionDuration === "string" ? transitionDuration : `${transitionDuration}ms`;
    }

    node.style[size] = collapsedSize;
    if (transitionTimingFunction) {
      node.style.transitionTimingFunction = transitionTimingFunction;
    }

    onExiting?.(node);
  });

  const handleAddEndListener = (done: () => void) => {
    if (timeout === "auto") {
      if (timerRef.current) {
        clearTimeout(timerRef.current);
      }
      timerRef.current = setTimeout(done, autoTransitionDuration.current || 0);
    }
    if (addEndListener && nodeRef.current) {
      addEndListener(nodeRef.current, done);
    }
  };

  const timeoutProps =
    timeout === "auto"
      ? { addEndListener: handleAddEndListener }
      : { timeout, addEndListener: handleAddEndListener };

  return (
    <Transition
      appear={appear}
      in={inProp}
      onEnter={handleEnter}
      onEntered={handleEntered}
      onEntering={handleEntering}
      onExit={handleExit}
      onExited={handleExited}
      onExiting={handleExiting}
      nodeRef={nodeRef}
      mountOnEnter={mountOnEnter}
      unmountOnExit={unmountOnExit}
      {...timeoutProps}
      {...other}
    >
      {(state) => {
        const hidden = state === "exited" && !inProp && collapsedSize === "0px";
        const entered = state === "entered";

        // Size is driven by CSS (0 / auto) + imperative node.style during enter/exit.
        // Do not put height/width on the React style prop — that overwrites the px
        // lock from onExit and collapses instantly.
        const rootStyle: CSSProperties = {
          ...(isHorizontal ? { minWidth: collapsedSize } : { minHeight: collapsedSize }),
          ...style,
        };

        return (
          <div
            ref={handleRef}
            className={mergeClassNames(
              "okkly-collapse",
              `okkly-collapse--${orientation}`,
              entered && "okkly-collapse--entered",
              hidden && "okkly-collapse--hidden",
              className,
            )}
            style={rootStyle}
          >
            <div ref={wrapperRef} className="okkly-collapse__wrapper">
              <div className="okkly-collapse__wrapper-inner">{children}</div>
            </div>
          </div>
        );
      }}
    </Transition>
  );
});

// packages/vue/src/components/Collapse/Collapse.vue
<script setup lang="ts">
import {
  computed,
  normalizeClass,
  normalizeStyle,
  onMounted,
  ref,
  useAttrs,
  useTemplateRef,
  watch,
} from "vue";
import "@okkly/design-system/components/Collapse/Collapse.scss";
import {
  DURATION_STANDARD,
  reflow,
  resolveTransitionDuration,
  resolveTransitionEasing,
} from "../../helpers/transitions";
import type { CollapseProps } from "./Collapse.types";

const props = withDefaults(defineProps<CollapseProps>(), {
  in: false,
  appear: true,
  easing: undefined,
  timeout: DURATION_STANDARD,
  orientation: "vertical",
  collapsedSize: "0px",
  unmountOnExit: false,
});

const emit = defineEmits<{
  enter: [node: HTMLElement];
  entered: [node: HTMLElement];
  exit: [node: HTMLElement];
  exited: [node: HTMLElement];
}>();

defineSlots<{
  /** The content Collapse reveals and hides. */
  default?: () => unknown;
}>();

// Collapse owns its own wrapper structure — unlike the rest of the family it
// never removes the outer element, so there is no `<slot>`-ownership problem
// to route around: everything below is a plain template ref on this
// component's own markup.
defineOptions({ inheritAttrs: false });
const attrs = useAttrs();
const root = useTemplateRef<HTMLDivElement>("root");
const wrapper = useTemplateRef<HTMLDivElement>("wrapper");

const isHorizontal = computed(() => props.orientation === "horizontal");
const sizeProp = computed<"width" | "height">(() => (isHorizontal.value ? "width" : "height"));
const collapsedSizeCss = computed(() =>
  typeof props.collapsedSize === "number" ? `${props.collapsedSize}px` : props.collapsedSize,
);

/** Mirrors the phase of a react-transition-group `Transition`, minus the mid-states. */
const phase = ref<"entered" | "exited" | "transitioning">(props.in ? "entered" : "exited");
const entered = computed(() => phase.value === "entered");
const hidden = computed(() => phase.value === "exited" && collapsedSizeCss.value === "0px");
const showContent = computed(() => !props.unmountOnExit || phase.value !== "exited");

const classes = computed(() =>
  normalizeClass([
    "okkly-collapse",
    `okkly-collapse--${props.orientation}`,
    entered.value && "okkly-collapse--entered",
    hidden.value && "okkly-collapse--hidden",
    attrs.class,
  ]),
);

// Size is driven by CSS (0 / auto) plus the imperative `node.style` writes
// during enter/exit — `collapsedSizeCss` here is only the resting minimum,
// never the animated dimension itself, or it would fight those writes.
const rootStyle = computed(() => [
  isHorizontal.value ? { minWidth: collapsedSizeCss.value } : { minHeight: collapsedSizeCss.value },
  normalizeStyle(attrs.style),
]);

function getWrapperSize(): number {
  const el = wrapper.value;
  if (!el) return 0;
  return isHorizontal.value ? el.clientWidth : el.clientHeight;
}

function runEnter() {
  const node = root.value;
  if (!node) return;
  phase.value = "transitioning";
  if (wrapper.value && isHorizontal.value) wrapper.value.style.position = "absolute";
  node.style[sizeProp.value] = collapsedSizeCss.value;
  emit("enter", node);

  // Force the collapsed size above to paint before measuring and animating to
  // the real size — otherwise both writes land in the same frame and nothing
  // appears to move.
  reflow(node);

  const wrapperSize = getWrapperSize();
  if (wrapper.value && isHorizontal.value) wrapper.value.style.position = "";
  const duration = resolveTransitionDuration(props.timeout, "enter", wrapperSize);
  const easing = resolveTransitionEasing(props.easing, "enter");
  node.style.transitionDuration = `${duration}ms`;
  node.style.transitionTimingFunction = easing;
  node.style[sizeProp.value] = `${wrapperSize}px`;

  window.setTimeout(() => {
    node.style[sizeProp.value] = "auto";
    phase.value = "entered";
    emit("entered", node);
  }, duration);
}

function runExit() {
  const node = root.value;
  if (!node) return;
  // Lock the current size in px before leaving `height/width: auto`.
  node.style[sizeProp.value] = `${getWrapperSize()}px`;
  emit("exit", node);
  reflow(node);

  phase.value = "transitioning";
  const wrapperSize = getWrapperSize();
  const duration = resolveTransitionDuration(props.timeout, "exit", wrapperSize);
  const easing = resolveTransitionEasing(props.easing, "exit");
  node.style.transitionDuration = `${duration}ms`;
  node.style.transitionTimingFunction = easing;
  node.style[sizeProp.value] = collapsedSizeCss.value;

  window.setTimeout(() => {
    phase.value = "exited";
    emit("exited", node);
  }, duration);
}

onMounted(() => {
  const node = root.value;
  if (!node) return;
  if (props.in) {
    if (props.appear) {
      runEnter();
      return;
    }
    node.style[sizeProp.value] = "auto";
    phase.value = "entered";
    return;
  }
  node.style[sizeProp.value] = collapsedSizeCss.value;
});

watch(
  () => props.in,
  (isIn) => {
    if (isIn) runEnter();
    else runExit();
  },
);
</script>

<template>
  <div ref="root" :class="classes" :style="rootStyle">
    <div ref="wrapper" class="okkly-collapse__wrapper">
      <div class="okkly-collapse__wrapper-inner">
        <template v-if="showContent">
          <slot />
        </template>
      </div>
    </div>
  </div>
</template>
