// packages/vue/src/components/Only/Only.vue
<script lang="ts">
import type { OnlyBreakpoint } from "./Only.types";

// Mirrors $breakpoints in packages/design-system/src/styles/breakpoints.scss —
// keep the two in sync when a breakpoint value changes.
const BREAKPOINT_PX: Record<OnlyBreakpoint, number> = {
  "2xs": 320,
  xs: 577,
  sm: 769,
  md: 993,
  lg: 1441,
  xl: 1921,
};

function buildQuery(from: OnlyBreakpoint | undefined, to: OnlyBreakpoint | undefined): string {
  const conditions: string[] = [];
  if (from) conditions.push(`(min-width: ${BREAKPOINT_PX[from]}px)`);
  if (to) conditions.push(`(max-width: ${BREAKPOINT_PX[to] - 1}px)`);
  return conditions.length > 0 ? conditions.join(" and ") : "all";
}
</script>

<script setup lang="ts">
import { useMediaQuery } from "@okkly/vue-composables";
import type { OnlyProps } from "./Only.types";

const props = defineProps<OnlyProps>();

defineSlots<{
  /** Rendered only while the viewport is within `[from, to)`. */
  default?: () => unknown;
}>();

const matches = useMediaQuery(() => buildQuery(props.from, props.to));
</script>

<template>
  <slot v-if="matches" />
</template>

// packages/react/src/components/Only/Only.tsx
"use client";

import { useMediaQuery } from "@okkly/react-hooks";
import type { OnlyBreakpoint, OnlyProps } from "./Only.types";

// Mirrors $breakpoints in packages/design-system/src/styles/breakpoints.scss —
// keep the two in sync when a breakpoint value changes.
const BREAKPOINT_PX: Record<OnlyBreakpoint, number> = {
  "2xs": 320,
  xs: 577,
  sm: 769,
  md: 993,
  lg: 1441,
  xl: 1921,
};

function buildQuery(from: OnlyBreakpoint | undefined, to: OnlyBreakpoint | undefined): string {
  const conditions: string[] = [];
  if (from) conditions.push(`(min-width: ${BREAKPOINT_PX[from]}px)`);
  if (to) conditions.push(`(max-width: ${BREAKPOINT_PX[to] - 1}px)`);
  return conditions.length > 0 ? conditions.join(" and ") : "all";
}

/**
 * Renders its children only while the viewport is within `[from, to)`. Omit
 * `from` for "up to `to`", omit `to` for "`from` and up", omit both to always
 * render. Unlike CSS-based hiding, children outside the range are never mounted.
 */
export function Only({ from, to, children }: OnlyProps) {
  const matches = useMediaQuery(buildQuery(from, to));
  return matches ? children : null;
}
