// packages/vue/src/components/DateTimePicker/DateTimePicker.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, useTemplateRef } from "vue";
import { iconArrowRight, iconGlobe } from "@okkly/icons";
import "@okkly/design-system/components/DateTimePicker/DateTimePicker.scss";
import Calendar, { calendarToneStyle } from "../Calendar/Calendar.vue";
import type { CalendarValue } from "../Calendar/Calendar.types";
import TimePicker from "../TimePicker/TimePicker.vue";
import type { TimePickerFormat, TimePickerValue } from "../TimePicker/TimePicker.types";
import Chip from "../Chip/Chip.vue";
import Button from "../Button/Button.vue";
import type { DateTimePickerProps } from "./DateTimePicker.types";

function startOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function timeOf(date: Date): TimePickerValue {
  return { h: date.getHours(), m: date.getMinutes() };
}

function combine(day: Date, time: TimePickerValue): Date {
  return new Date(day.getFullYear(), day.getMonth(), day.getDate(), time.h, time.m);
}

function formatSummary(date: Date, locale: string, format: TimePickerFormat): string {
  const datePart = date.toLocaleDateString(locale, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  const timePart = date.toLocaleTimeString(locale, {
    hour: "2-digit",
    minute: "2-digit",
    hour12: format === "12h",
  });
  return `${datePart} · ${timePart}`;
}

const props = withDefaults(defineProps<DateTimePickerProps>(), {
  min: undefined,
  max: undefined,
  defaultValue: null,
  timeStep: 1,
  format: "24h",
  weekStart: "mon",
  color: "primary",
  locale: "en-US",
  previousMonthLabel: undefined,
  nextMonthLabel: undefined,
});

// The returned object is the runtime slots record — using it directly avoids
// the circular inference `useSlots()` hits when the same file declares them.
const slots = defineSlots<{
  /** Trailing chip next to the summary text (e.g. a timezone, "GMT+2"). Omitted when not filled. */
  "timezone-label"?: () => unknown;
  /** Label shown above the summary text. */
  "summary-label"?: () => unknown;
  /** Summary text shown before any date has been picked. */
  "empty-label"?: () => unknown;
  /** Confirm button label. */
  "confirm-label"?: () => unknown;
}>();

const emit = defineEmits<{
  confirm: [value: Date];
}>();

// Unlike React's manual `value !== undefined ? value : internalValue` split,
// `model.value` already resolves controlled vs. uncontrolled — `undefined`
// means genuinely unbound, so it's the only case that falls back to
// `defaultValue`. Comparing against it with `!==`, not `??`, matters because
// a controlled `null` (deliberately "no date") must not be mistaken for "unset".
const model = defineModel<Date | null>();
const currentValue = computed<Date | null>(() =>
  model.value !== undefined ? model.value : (props.defaultValue ?? null),
);

// The time wheels stay interactive even before a day is picked — this remembers
// the dialed-in hour/minute so it carries over once a day finally lands, instead
// of the wheels resetting to 0:00 or silently committing a bogus "today" value.
const draftTime = ref<TimePickerValue>(
  currentValue.value ? timeOf(currentValue.value) : { h: 0, m: 0 },
);
const month = ref<Date>(currentValue.value ?? new Date());

const day = computed(() => (currentValue.value ? startOfDay(currentValue.value) : null));
const time = computed(() => (currentValue.value ? timeOf(currentValue.value) : draftTime.value));

// Measures the calendar *panel* rather than its root: the root is a plain
// wrapper, and the bordered card inside it is what the time wheels line up to.
const calendarRef = useTemplateRef<InstanceType<typeof Calendar>>("calendarRef");
const calendarHeight = ref<number | null>(null);

onMounted(() => {
  const root = calendarRef.value?.$el as HTMLElement | undefined;
  if (!root || typeof ResizeObserver === "undefined") return;
  const panel = root.querySelector<HTMLElement>(".okkly-calendar__panel") ?? root;
  // `offsetHeight`, not `getBoundingClientRect()`: inside a field's popover
  // this mounts during a Grow transition, and a rect measured mid-`scale()`
  // reports a fraction of the real height — which then stuck, because
  // ResizeObserver never fires for a transform.
  const update = () => {
    calendarHeight.value = panel.offsetHeight;
  };
  update();
  const observer = new ResizeObserver(update);
  observer.observe(panel);
  onUnmounted(() => observer.disconnect());
});

const timePickerStyle = computed(() =>
  calendarHeight.value != null
    ? { "--okkly-time-picker-viewport-height": `calc(${calendarHeight.value}px - 1.125rem)` }
    : undefined,
);

function commit(next: Date) {
  model.value = next;
}

function handleSelectDay(date: Date) {
  commit(combine(date, time.value));
}

// `mode="single"` is never overridden, so `value` is always `Date | null`.
function handleCalendarChange(value: CalendarValue | null) {
  if (value instanceof Date) handleSelectDay(value);
}

function handleTimeChange(next: TimePickerValue | undefined) {
  if (!next) return;
  draftTime.value = next;
  if (day.value) commit(combine(day.value, next));
}

function handleConfirm() {
  if (currentValue.value) emit("confirm", currentValue.value);
}

const classes = "okkly-component okkly-date-time-picker";
const toneStyle = computed(() => calendarToneStyle(props.color));

const formattedSummary = computed(() =>
  currentValue.value ? formatSummary(currentValue.value, props.locale, props.format) : "",
);
const summaryTextClasses = computed(() =>
  [
    "okkly-date-time-picker__summary-text",
    !currentValue.value && "okkly-date-time-picker__summary-text--empty",
  ]
    .filter(Boolean)
    .join(" "),
);
const showTimezoneChip = computed(() => !!slots["timezone-label"]);
</script>

<template>
  <div :class="classes">
    <div class="okkly-date-time-picker__panels">
      <Calendar
        ref="calendarRef"
        :style="toneStyle"
        v-model:month="month"
        :model-value="day"
        :min="min"
        :max="max"
        :week-start="weekStart"
        :locale="locale"
        :previous-month-label="previousMonthLabel"
        :next-month-label="nextMonthLabel"
        @update:model-value="handleCalendarChange"
      />
      <TimePicker
        :model-value="time"
        :step="timeStep"
        :format="format"
        :color="color"
        :style="timePickerStyle"
        @update:model-value="handleTimeChange"
      />
    </div>
    <div class="okkly-date-time-picker__footer">
      <div class="okkly-date-time-picker__summary">
        <p class="okkly-date-time-picker__summary-label">
          <slot name="summary-label">Selected time</slot>
        </p>
        <div class="okkly-date-time-picker__summary-value">
          <span :class="summaryTextClasses">
            <template v-if="currentValue">{{ formattedSummary }}</template>
            <slot v-else name="empty-label">No date selected</slot>
          </span>
          <Chip v-if="showTimezoneChip" size="small">
            <template #icon>
              <span aria-hidden="true" v-html="iconGlobe" />
            </template>
            <slot name="timezone-label" />
          </Chip>
        </div>
      </div>
      <Button
        variant="gradient"
        shape="rounded"
        :color="color"
        :disabled="!currentValue"
        @click="handleConfirm"
      >
        <template #end-icon>
          <span aria-hidden="true" v-html="iconArrowRight" />
        </template>
        <slot name="confirm-label">Confirm</slot>
      </Button>
    </div>
  </div>
</template>

// packages/angular/src/components/DateTimePicker/DateTimePicker.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  afterRenderEffect,
  computed,
  input,
  model,
  output,
  signal,
  viewChild,
  type ElementRef,
} from "@angular/core";
import { iconArrowRight, iconGlobe } from "@okkly/icons";
import { OkklyButton, OkklyButtonEndIcon } from "../Button/Button";
import { OkklyCalendar } from "../Calendar/Calendar";
import {
  startOfDay,
  type CalendarTone,
  type CalendarValue,
  type CalendarWeekStart,
} from "../Calendar/dates";
import { OkklyChip, OkklyChipIcon } from "../Chip/Chip";
import { OkklyIcon } from "../Icon/Icon";
import {
  OkklyTimePicker,
  type TimePickerFormat,
  type TimePickerValue,
} from "../TimePicker/TimePicker";

export type DateTimePickerColor = CalendarTone;
export type { TimePickerFormat };

function timeOf(date: Date): TimePickerValue {
  return { h: date.getHours(), m: date.getMinutes() };
}

function combine(day: Date, time: TimePickerValue): Date {
  return new Date(day.getFullYear(), day.getMonth(), day.getDate(), time.h, time.m);
}

function formatSummary(date: Date, locale: string, format: TimePickerFormat): string {
  const datePart = date.toLocaleDateString(locale, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  const timePart = date.toLocaleTimeString(locale, {
    hour: "2-digit",
    minute: "2-digit",
    hour12: format === "12h",
  });
  return `${datePart} · ${timePart}`;
}

/**
 * No MUI equivalent as a fixed inline card — MUI X's `DateTimePicker` is a
 * masked text input with a popover (that's `OkklyDateTimeField`, which
 * embeds this). Composed from `OkklyCalendar` + `OkklyTimePicker`.
 * Deliberate gaps: only a date → use `OkklyCalendar`; only a time → use
 * `OkklyTimePicker`; no shortcut-preset sidebar (one line of caller code
 * against `value` covers it). `value` is a two-way `model()`
 * (`[(value)]`) standing in for react's `value`/`defaultValue`+`onChange`.
 * `summaryLabel`/`emptyLabel`/`confirmLabel`/`timezoneLabel` are plain
 * `string`s, not `ReactNode` — Angular has no such equivalent.
 */
@Component({
  selector: "okkly-date-time-picker",
  changeDetection: ChangeDetectionStrategy.OnPush,
  // Every rule this renders lives in @okkly/design-system as a global BEM
  // class inside the `okkly` cascade layer; scoping attributes would only add
  // noise to the DOM.
  encapsulation: ViewEncapsulation.None,
  host: { class: "okkly-component okkly-date-time-picker" },
  imports: [
    OkklyButton,
    OkklyButtonEndIcon,
    OkklyCalendar,
    OkklyChip,
    OkklyChipIcon,
    OkklyIcon,
    OkklyTimePicker,
  ],
  templateUrl: "./DateTimePicker.html",
})
export class OkklyDateTimePicker {
  /**
   * Selected date & time. Two-way bindable as `[(value)]`.
   *
   * @default null
   */
  readonly value = model<Date | null>(null);
  /**
   * Earliest selectable date (inclusive).
   *
   * @default undefined
   */
  readonly min = input<Date>();
  /**
   * Latest selectable date (inclusive).
   *
   * @default undefined
   */
  readonly max = input<Date>();
  /**
   * Minute wheel step.
   *
   * @default 1
   */
  readonly timeStep = input(1);
  /**
   * Hour wheel label format — the underlying value stays 24-hour either way.
   *
   * @default "24h"
   */
  readonly format = input<TimePickerFormat>("24h");
  /**
   * First day of the week.
   *
   * @default "mon"
   */
  readonly weekStart = input<CalendarWeekStart>("mon");
  /**
   * Accent tone shared by the calendar, the time wheels, and the Confirm button's glow.
   *
   * @default "primary"
   */
  readonly color = input<DateTimePickerColor>("primary");
  /**
   * Locale for the month title, weekday labels, and the summary text.
   *
   * @default "en-US"
   */
  readonly locale = input("en-US");
  /**
   * Trailing chip next to the summary text (e.g. a timezone, "GMT+2"). Omitted when unset.
   *
   * @default undefined
   */
  readonly timezoneLabel = input<string>();
  /**
   * Label shown above the summary text.
   *
   * @default "Selected time"
   */
  readonly summaryLabel = input("Selected time");
  /**
   * Summary text shown before any date has been picked.
   *
   * @default "No date selected"
   */
  readonly emptyLabel = input("No date selected");
  /**
   * Confirm button label.
   *
   * @default "Confirm"
   */
  readonly confirmLabel = input("Confirm");
  /**
   * Accessible name for the calendar's "previous month" button.
   *
   * @default undefined
   */
  readonly previousMonthLabel = input<string>();
  /**
   * Accessible name for the calendar's "next month" button.
   *
   * @default undefined
   */
  readonly nextMonthLabel = input<string>();

  /** Fires when the Confirm button is clicked. */
  readonly confirm = output<Date>();

  protected readonly iconArrowRight = iconArrowRight;
  protected readonly iconGlobe = iconGlobe;

  // The time wheels stay interactive even before a day is picked — this
  // remembers the dialed-in hour/minute so it carries over once a day
  // finally lands, instead of the wheels resetting to 0:00 or silently
  // committing a bogus "today" value the instant a wheel moves.
  private readonly draftTime = signal<TimePickerValue>(
    this.value() ? timeOf(this.value()!) : { h: 0, m: 0 },
  );
  // Separate from `value` so browsing months while nothing is picked yet has
  // no effect on the committed value — mirrors `OkklyCalendar`'s own
  // `month`/`(monthChange)` controlled pair, just owned here instead.
  protected readonly month = signal<Date | undefined>(this.value() ?? undefined);

  protected readonly day = computed<Date | null>(() => {
    const value = this.value();
    return value ? startOfDay(value) : null;
  });
  protected readonly time = computed<TimePickerValue>(() => {
    const value = this.value();
    return value ? timeOf(value) : this.draftTime();
  });

  protected readonly summaryText = computed(() => {
    const value = this.value();
    return value ? formatSummary(value, this.locale(), this.format()) : this.emptyLabel();
  });

  // Measures the calendar's own bordered panel (not its root, a plain
  // wrapper) so the time-picker card beside it can match its height exactly.
  // `offsetHeight`, not `getBoundingClientRect()`: this often mounts inside a
  // Grow transition, whose `transform: scale()` would otherwise be measured
  // as a smaller panel. `OkklyCalendar` exposes no native-element handle of
  // its own, so `#calendarHost` wraps it — `display: contents` in the
  // template keeps that wrapper invisible to the `&__panels` flex row.
  private readonly calendarHost = viewChild<ElementRef<HTMLElement>>("calendarHost");
  private readonly panelHeight = signal<number | null>(null);
  protected readonly timePickerViewportHeight = computed(() => {
    const height = this.panelHeight();
    return height != null ? `calc(${height}px - 1.125rem)` : null;
  });

  constructor() {
    afterRenderEffect((onCleanup) => {
      const host = this.calendarHost()?.nativeElement;
      if (!host || typeof ResizeObserver === "undefined") return;
      const panel = host.querySelector<HTMLElement>(".okkly-calendar__panel") ?? host;
      const update = () => this.panelHeight.set(panel.offsetHeight);
      update();
      const observer = new ResizeObserver(update);
      observer.observe(panel);
      onCleanup(() => observer.disconnect());
    });
  }

  protected handleSelectDay(next: CalendarValue | null): void {
    if (!next || Array.isArray(next)) return;
    this.value.set(combine(next, this.time()));
  }

  protected handleTimeChange(next: TimePickerValue): void {
    this.draftTime.set(next);
    const day = this.day();
    if (day) this.value.set(combine(day, next));
  }

  protected onConfirmClick(): void {
    const value = this.value();
    if (value) this.confirm.emit(value);
  }
}
