// packages/react/src/components/Ripple/Ripple.tsx
import "@okkly/design-system/components/Ripple/Ripple.scss";

import type { RippleProps } from "./Ripple.types";

/** Presentational overlay for `useRipple` — the trigger element owns `position: relative; overflow: hidden`. */
export function Ripple({ ripples, onRippleEnd }: RippleProps) {
  return (
    <span className="okkly-component okkly-ripple" aria-hidden="true">
      {[...ripples].map(([id, ripple]) => (
        <span
          key={id}
          className="okkly-ripple__element"
          data-rippleid={id}
          style={
            {
              "--okkly-ripple-left": ripple.left,
              "--okkly-ripple-top": ripple.top,
            } as React.CSSProperties
          }
          onAnimationEnd={(e) => onRippleEnd((e.currentTarget as HTMLElement).dataset.rippleid)}
        />
      ))}
    </span>
  );
}

// packages/vue/src/components/Ripple/Ripple.vue
<script setup lang="ts">
import "@okkly/design-system/components/Ripple/Ripple.scss";
import type { RippleProps } from "./Ripple.types";

defineProps<RippleProps>();
</script>

<!-- Presentational overlay for `useRipple` — the trigger element owns `position: relative; overflow: hidden`. -->
<template>
  <span class="okkly-component okkly-ripple" aria-hidden="true">
    <span
      v-for="[id, ripple] in ripples"
      :key="id"
      class="okkly-ripple__element"
      :data-rippleid="id"
      :style="{ '--okkly-ripple-left': ripple.left, '--okkly-ripple-top': ripple.top }"
      @animationend="onRippleEnd(($event.currentTarget as HTMLElement).dataset.rippleid)"
    />
  </span>
</template>
