// packages/react/src/components/Badge/Badge.tsx
"use client";

import { type ReactNode } from "react";
import "@okkly/design-system/components/Badge/Badge.scss";
import type { BadgeVariant, BadgeProps } from "./Badge.types";

function formatContent(content: ReactNode, max: number): ReactNode {
  if (content == null || content === false) return null;
  if (typeof content === "number") {
    if (content === 0) return null;
    if (content > max) return `${max}+`;
  }
  return content;
}

function shouldHide(content: ReactNode, invisible: boolean, variant: BadgeVariant) {
  if (invisible) return true;
  if (variant === "dot") return false;
  return content == null || content === false || content === 0;
}

export function Badge({
  badgeContent,
  children,
  color,
  variant = "standard",
  max = 99,
  invisible = false,
  overlap = "circular",
  anchorOrigin = { vertical: "top", horizontal: "right" },
  className,
}: BadgeProps) {
  const formatted = variant === "dot" ? null : formatContent(badgeContent, max);
  const hidden = shouldHide(formatted, invisible, variant);
  const standalone = children == null;

  const rootClasses = [
    "okkly-component",
    "okkly-badge",
    standalone && "okkly-badge--standalone",
    overlap === "rectangular" && "okkly-badge--overlap-rectangular",
    color && `okkly-badge--color-${color}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const contentClasses = [
    "okkly-badge__content",
    variant === "dot" && "okkly-badge__content--dot",
    hidden && "okkly-badge__content--invisible",
    !standalone && `okkly-badge__content--${anchorOrigin.vertical}`,
    !standalone && `okkly-badge__content--${anchorOrigin.horizontal}`,
  ]
    .filter(Boolean)
    .join(" ");

  const badgeNode = (
    <span
      className={contentClasses}
      data-testid="badge-content"
      aria-hidden={variant === "dot" || hidden ? true : undefined}
    >
      {variant === "standard" ? formatted : null}
    </span>
  );

  if (standalone) {
    return <span className={rootClasses}>{badgeNode}</span>;
  }

  return (
    <span className={rootClasses}>
      <span className="okkly-badge__anchor">{children}</span>
      {badgeNode}
    </span>
  );
}

// packages/vue/src/components/Badge/Badge.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import "@okkly/design-system/components/Badge/Badge.scss";
import type { BadgeProps } from "./Badge.types";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BadgeProps>(), {
  variant: "standard",
  max: 99,
  invisible: false,
  overlap: "circular",
  anchorOrigin: () => ({ vertical: "top", horizontal: "right" }),
});

defineSlots<{
  /** Element the badge anchors to. Omit for a standalone pill/dot. */
  default?: () => unknown;
}>();

const slots = useSlots();
const standalone = computed(() => !slots.default);

const formatted = computed<string | number | undefined>(() => {
  if (props.variant === "dot") return undefined;
  const content = props.badgeContent;
  if (content == null) return undefined;
  if (typeof content === "number") {
    if (content === 0) return undefined;
    if (content > props.max) return `${props.max}+`;
  }
  return content;
});

const hidden = computed(() => {
  if (props.invisible) return true;
  if (props.variant === "dot") return false;
  return formatted.value == null;
});

const rootClasses = computed(() =>
  [
    "okkly-component",
    "okkly-badge",
    standalone.value && "okkly-badge--standalone",
    props.overlap === "rectangular" && "okkly-badge--overlap-rectangular",
    props.color && `okkly-badge--color-${props.color}`,
  ]
    .filter(Boolean)
    .join(" "),
);

const contentClasses = computed(() =>
  [
    "okkly-badge__content",
    props.variant === "dot" && "okkly-badge__content--dot",
    hidden.value && "okkly-badge__content--invisible",
    !standalone.value && `okkly-badge__content--${props.anchorOrigin.vertical}`,
    !standalone.value && `okkly-badge__content--${props.anchorOrigin.horizontal}`,
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <span :class="rootClasses" v-bind="$attrs">
    <span v-if="!standalone" class="okkly-badge__anchor"><slot /></span>
    <span
      :class="contentClasses"
      data-testid="badge-content"
      :aria-hidden="variant === 'dot' || hidden ? true : undefined"
      >{{ variant === "standard" ? formatted : "" }}</span
    >
  </span>
</template>
