// packages/vue/src/components/Rating/Rating.vue
<script lang="ts">
function defaultGetLabelText(value: number): string {
  return `${value} Star${value !== 1 ? "s" : ""}`;
}

function starKind(displayValue: number, index: number): "full" | "half" | "empty" {
  const position = index + 1;
  if (displayValue >= position) return "full";
  if (displayValue >= position - 0.5) return "half";
  return "empty";
}

function valueFromPointer(event: MouseEvent, index: number, precision: 0.5 | 1): number {
  if (precision === 1) return index + 1;
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  const ratio = (event.clientX - rect.left) / rect.width;
  return ratio <= 0.5 ? index + 0.5 : index + 1;
}
</script>

<script setup lang="ts">
import { computed, ref } from "vue";
import "@okkly/design-system/components/Rating/Rating.scss";
import RatingGlyph from "./RatingGlyph.vue";
import type { RatingProps } from "./Rating.types";

const props = withDefaults(defineProps<RatingProps>(), {
  defaultValue: null,
  max: 5,
  precision: 0.5,
  size: "medium",
  color: "warning",
  icon: "star",
  readOnly: false,
  disabled: false,
  name: undefined,
  getLabelText: defaultGetLabelText,
});

const slots = defineSlots<{
  /** Custom filled glyph, overriding the built-in `"star"`/`"heart"` shape. */
  icon?: () => unknown;
  /** Trailing summary (e.g. "4.8 · 128 reviews"). */
  label?: () => unknown;
}>();

// Unlike React's manual `value !== undefined ? value : internalValue` split,
// `model.value` already resolves controlled vs. uncontrolled — `undefined`
// means genuinely unbound, so it's the only case that falls back to
// `defaultValue`.
const model = defineModel<number | null>();
const resolvedValue = computed<number | null>(() =>
  model.value !== undefined ? model.value : props.defaultValue,
);

const hoverValue = ref<number | null>(null);
const displayValue = computed(() => hoverValue.value ?? resolvedValue.value ?? 0);

function commit(next: number | null) {
  model.value = next;
}

function handleItemClick(event: MouseEvent, index: number) {
  if (props.readOnly || props.disabled) return;
  const next = valueFromPointer(event, index, props.precision);
  if (next === resolvedValue.value) commit(null);
  else commit(next);
}

function handleItemMove(event: MouseEvent, index: number) {
  if (props.readOnly || props.disabled) return;
  hoverValue.value = valueFromPointer(event, index, props.precision);
}

function handleKeyDown(event: KeyboardEvent) {
  if (props.readOnly || props.disabled) return;
  const step = props.precision;
  const base = resolvedValue.value ?? 0;

  if (event.key === "ArrowRight" || event.key === "ArrowUp") {
    event.preventDefault();
    commit(Math.min(props.max, base + step));
  } else if (event.key === "ArrowLeft" || event.key === "ArrowDown") {
    event.preventDefault();
    commit(Math.max(0, base - step) || null);
  }
}

const stars = computed(() =>
  Array.from({ length: props.max }, (_, index) => ({
    index,
    kind: starKind(displayValue.value, index),
    label: props.getLabelText(index + 1),
  })),
);

const interactive = computed(() => !props.readOnly && !props.disabled);

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-rating",
    props.color !== "warning" && `okkly-rating--color-${props.color}`,
    props.size !== "medium" && `okkly-rating--${props.size}`,
    props.readOnly && "okkly-rating--read-only",
    props.disabled && "okkly-rating--disabled",
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <span
    :class="classes"
    :role="interactive ? 'radiogroup' : 'img'"
    :aria-label="!interactive ? `${displayValue} of ${max}` : undefined"
    @mouseleave="hoverValue = null"
  >
    <span class="okkly-rating__stars">
      <template v-for="star in stars" :key="star.index">
        <span v-if="!interactive" class="okkly-rating__item" aria-hidden="true">
          <RatingGlyph v-if="slots.icon" :kind="star.kind" :glyph="icon"
            ><slot name="icon"
          /></RatingGlyph>
          <RatingGlyph v-else :kind="star.kind" :glyph="icon" />
        </span>
        <button
          v-else
          type="button"
          class="okkly-rating__item"
          :name="name"
          :aria-label="star.label"
          @click="handleItemClick($event, star.index)"
          @mousemove="handleItemMove($event, star.index)"
          @keydown="handleKeyDown"
        >
          <RatingGlyph v-if="slots.icon" :kind="star.kind" :glyph="icon"
            ><slot name="icon"
          /></RatingGlyph>
          <RatingGlyph v-else :kind="star.kind" :glyph="icon" />
        </button>
      </template>
    </span>
    <span v-if="slots.label" class="okkly-rating__label"><slot name="label" /></span>
  </span>
</template>

// packages/angular/src/components/Rating/Rating.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  TemplateRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  contentChild,
  inject,
  input,
  model,
  numberAttribute,
  signal,
} from "@angular/core";

export type RatingSize = "small" | "medium" | "large";
export type RatingColor = "warning" | "primary" | "dante" | "indigo" | "violet" | "ember" | "ice";
export type RatingIcon = "star" | "heart";
export type RatingPrecision = 0.5 | 1;

/** How much of one glyph is filled. */
type GlyphKind = "full" | "half" | "empty";

/**
 * Replaces the built-in glyph: `<ng-template okklyRatingIcon>…</ng-template>`.
 * Stamped once per glyph (twice for a half one), so it is a template rather
 * than projected content.
 */
@Directive({ selector: "ng-template[okklyRatingIcon]" })
export class OkklyRatingIcon {
  readonly template = inject(TemplateRef);
}

function defaultGetLabelText(value: number): string {
  return `${value} Star${value !== 1 ? "s" : ""}`;
}

/**
 * A row of stars (or hearts) to show or pick a score. Inputs follow MUI's
 * Rating, as `@okkly/react`'s `<Rating>` does — `value`, `max`, `precision`,
 * `size`, `color`, `icon`, `readOnly`, `disabled`, `label`, `name`,
 * `getLabelText`.
 *
 * Deliberate gaps: `value` is a `model<number | null>()` (`[(value)]`)
 * standing in for React's `value`/`defaultValue` + `onChange`. A custom glyph
 * is an `okklyRatingIcon` template rather than a node passed to `icon`, and
 * `label` is text.
 */
@Component({
  selector: "okkly-rating",
  changeDetection: ChangeDetectionStrategy.OnPush,
  // Every rule this renders lives in @okkly/design-system as a global BEM
  // class inside the `okkly` cascade layer; scoping attributes would only add
  // noise to the DOM.
  encapsulation: ViewEncapsulation.None,
  imports: [NgTemplateOutlet],
  host: {
    class: "okkly-component okkly-rating",
    "[class]": "modifiers()",
    "[attr.role]": "interactive() ? 'radiogroup' : 'img'",
    "[attr.aria-label]": "interactive() ? null : displayValue() + ' of ' + max()",
    "[attr.name]": "null",
    "(mouseleave)": "hoverValue.set(null)",
  },
  templateUrl: "./Rating.html",
})
export class OkklyRating {
  /**
   * Current score, `null` for none. Two-way bindable as `[(value)]`.
   *
   * @default null
   */
  readonly value = model<number | null>(null);
  /**
   * Number of glyphs.
   *
   * @default 5
   */
  readonly max = input(5, { transform: numberAttribute });
  /**
   * Smallest step a score can take: half glyphs (`0.5`) or whole ones (`1`).
   *
   * @default 0.5
   */
  readonly precision = input<RatingPrecision, unknown>(0.5, {
    transform: (value) => (numberAttribute(value, 0.5) === 1 ? 1 : 0.5),
  });
  /**
   * Glyph size.
   *
   * @default "medium"
   */
  readonly size = input<RatingSize>("medium");
  /**
   * Fill colour — the default gold is `--okkly-feedback-warning`.
   *
   * @default "warning"
   */
  readonly color = input<RatingColor>("warning");
  /**
   * Built-in glyph. An `okklyRatingIcon` template wins over it.
   *
   * @default "star"
   */
  readonly icon = input<RatingIcon>("star");
  /**
   * Display only — no hover or click.
   *
   * @default false
   */
  readonly readOnly = input(false, { transform: booleanAttribute });
  /**
   * Non-interactive and dimmed.
   *
   * @default false
   */
  readonly disabled = input(false, { transform: booleanAttribute });
  /**
   * Trailing summary, e.g. "4.8 · 128 reviews".
   *
   * @default undefined
   */
  readonly label = input<string>();
  /**
   * Set on each interactive glyph button, for form grouping.
   *
   * @default undefined
   */
  readonly name = input<string>();
  /**
   * Accessible name of each glyph button, from the score it picks.
   *
   * @default "1 Star", "2 Stars", …
   */
  readonly getLabelText = input<(value: number) => string>(defaultGetLabelText);

  protected readonly customIcon = contentChild(OkklyRatingIcon);
  protected readonly hoverValue = signal<number | null>(null);

  protected readonly interactive = computed(() => !this.readOnly() && !this.disabled());
  protected readonly displayValue = computed(() => this.hoverValue() ?? this.value() ?? 0);
  protected readonly glyphs = computed(() => {
    const display = this.displayValue();
    return Array.from({ length: this.max() }, (_, index): GlyphKind => {
      const position = index + 1;
      if (display >= position) return "full";
      if (display >= position - 0.5) return "half";
      return "empty";
    });
  });

  protected readonly modifiers = computed(() =>
    [
      this.color() !== "warning" && `okkly-rating--color-${this.color()}`,
      this.size() !== "medium" && `okkly-rating--${this.size()}`,
      this.readOnly() && "okkly-rating--read-only",
      this.disabled() && "okkly-rating--disabled",
    ]
      .filter(Boolean)
      .join(" "),
  );

  private valueFromPointer(event: MouseEvent, index: number): number {
    if (this.precision() === 1) return index + 1;
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const ratio = (event.clientX - rect.left) / rect.width;
    return ratio <= 0.5 ? index + 0.5 : index + 1;
  }

  protected onClick(event: MouseEvent, index: number): void {
    if (!this.interactive()) return;
    const next = this.valueFromPointer(event, index);
    this.value.set(next === this.value() ? null : next);
  }

  protected onMove(event: MouseEvent, index: number): void {
    if (!this.interactive()) return;
    this.hoverValue.set(this.valueFromPointer(event, index));
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.interactive()) return;
    const step = this.precision();
    const base = this.value() ?? 0;
    if (event.key === "ArrowRight" || event.key === "ArrowUp") {
      event.preventDefault();
      this.value.set(Math.min(this.max(), base + step));
    } else if (event.key === "ArrowLeft" || event.key === "ArrowDown") {
      event.preventDefault();
      this.value.set(Math.max(0, base - step) || null);
    }
  }
}
