// packages/angular/src/components/Field/Field.ts
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  input,
} from "@angular/core";

export type FieldSize = "small" | "medium" | "large";
export type FieldColor =
  "primary" | "secondary" | "dante" | "violet" | "ember" | "ice" | "contrast";

/** Marks the projected element that renders in the control box's start adornment slot. */
@Directive({ selector: "[okklyFieldStartAdornment]" })
export class OkklyFieldStartAdornment {}

/** Marks the projected element that renders in the control box's end adornment slot. */
@Directive({ selector: "[okklyFieldEndAdornment]" })
export class OkklyFieldEndAdornment {}

/** Ids `OkklyField` derives from the control id, so a wrapper can wire aria attributes to them. */
export function getFieldIds(id: string, hasLabel: boolean, hasHelperText: boolean) {
  return {
    labelId: hasLabel ? `${id}-label` : undefined,
    helperId: hasHelperText ? `${id}-helper` : undefined,
  };
}

/**
 * The shared shell behind TextField, Select and Autocomplete: label row,
 * bordered control box with optional adornments, and helper text. Mirrors
 * `@okkly/react`'s internal `Field` component.
 *
 * Internal on purpose — not exported from `src/index.ts`. It exists to stop
 * its consumers from re-implementing (and slowly disagreeing about) focus
 * rings, error colours and label spacing, not to become a public layout
 * primitive. Its styling counterpart is the `field.shell` SCSS mixin.
 *
 * Deliberate gap: no equivalent of React's `controlProps`/`ref` on the control
 * box — no current consumer needs to anchor a popup on it yet. Adornment
 * presence is an explicit `hasStartAdornment`/`hasEndAdornment` input rather
 * than self-detected, because a wrapper (e.g. `OkklyTextField`) forwards
 * projected content through `ngProjectAs`, under which a `contentChild` query
 * here would never see the original marker directive.
 *
 * Attribute selector on the `<div>` its consumer (`OkklyTextField`, one day
 * `OkklySelect`) declares — an element selector would wrap that div in a
 * second, unstyled `<okkly-field>` tag, pushing the BEM block one level
 * deeper than React's single root `<div>`.
 */
@Component({
  selector: "div[okklyField]",
  changeDetection: ChangeDetectionStrategy.OnPush,
  // Every rule this renders lives in @okkly/design-system as a global BEM
  // class inside the `okkly` cascade layer; scoping attributes would only add
  // noise to the DOM.
  encapsulation: ViewEncapsulation.None,
  host: {
    "[class]": "hostClasses()",
  },
  templateUrl: "./Field.html",
})
export class OkklyField {
  /**
   * BEM block the emitted classes are namespaced under, e.g. `"okkly-text-field"`.
   * Each consumer keeps its own block so its public class names stay exactly what they were.
   */
  readonly block = input.required<string>();
  /** Id of the control this field wraps; the label's `for` and the helper id derive from it. */
  readonly id = input.required<string>();
  /**
   * Label.
   *
   * @default undefined
   */
  readonly label = input<string>();
  /**
   * Visually hides the label (still present for assistive tech).
   *
   * @default false
   */
  readonly hideLabel = input(false, { transform: booleanAttribute });
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   */
  readonly required = input(false, { transform: booleanAttribute });
  /**
   * Size.
   *
   * @default "medium"
   */
  readonly size = input<FieldSize>("medium");
  /**
   * Color.
   *
   * @default "primary"
   */
  readonly color = input<FieldColor>("primary");
  /**
   * Error.
   *
   * @default false
   */
  readonly error = input(false, { transform: booleanAttribute });
  /**
   * Helper text.
   *
   * @default undefined
   */
  readonly helperText = input<string>();
  /**
   * Disabled.
   *
   * @default false
   */
  readonly disabled = input(false, { transform: booleanAttribute });
  /**
   * Full width.
   *
   * @default false
   */
  readonly fullWidth = input(false, { transform: booleanAttribute });
  /**
   * `<label for>` only works for real form controls, so a wrapper whose control is not one
   * (a `div[role="combobox"]`, say) passes `false` and points at `${id}-label` with
   * `aria-labelledby` on the control itself instead.
   *
   * @default undefined
   */
  readonly htmlFor = input<string | false>();
  /**
   * Whether an element was projected into the start adornment slot.
   *
   * @default false
   */
  readonly hasStartAdornment = input(false, { transform: booleanAttribute });
  /**
   * Whether an element was projected into the end adornment slot.
   *
   * @default false
   */
  readonly hasEndAdornment = input(false, { transform: booleanAttribute });

  protected readonly labelId = computed(() => (this.label() ? `${this.id()}-label` : undefined));
  protected readonly helperId = computed(() =>
    this.helperText() ? `${this.id()}-helper` : undefined,
  );
  protected readonly computedFor = computed(() => {
    const htmlFor = this.htmlFor();
    return htmlFor === false ? null : (htmlFor ?? this.id());
  });

  protected readonly hostClasses = computed(() =>
    [
      "okkly-component",
      this.block(),
      this.color() !== "primary" && `${this.block()}--color-${this.color()}`,
      this.size() !== "medium" && `${this.block()}--${this.size()}`,
      this.error() && `${this.block()}--error`,
      this.disabled() && `${this.block()}--disabled`,
      this.fullWidth() && `${this.block()}--full-width`,
    ]
      .filter(Boolean)
      .join(" "),
  );
}

// packages/react/src/components/Field/Field.tsx
"use client";

import type { HTMLAttributes, Ref, ReactNode } from "react";

export type FieldSize = "small" | "medium" | "large";
export type FieldColor = "primary" | "dante";
/**
 * Every accent tint a `Field`-shell control can take. Broader than
 * `FieldColor`, which is what Select/Autocomplete/DateField/TimeField/etc.
 * still expose publicly — TextField is the one consumer that opts into the
 * full accent set.
 */
export type FieldAccentColor = FieldColor | "secondary" | "violet" | "ember" | "ice" | "contrast";

export interface FieldProps {
  /**
   * BEM block the emitted classes are namespaced under, e.g. `"okkly-select"`. Each consumer keeps its own block so its public class names — the ones apps target in overrides — stay exactly what they were.
   *
   * @default undefined
   * @type {string}
   */
  block: string;
  /**
   * Id of the control this field wraps; the label's `for` and the helper id derive from it.
   *
   * @default undefined
   * @type {string}
   */
  id: string;
  /**
   * Label.
   *
   * @default undefined
   * @type {ReactNode}
   */
  label?: ReactNode;
  /**
   * Hide Label.
   *
   * @default false
   * @type {boolean}
   */
  hideLabel?: boolean;
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   * @type {boolean}
   */
  required?: boolean;
  /**
   * Size.
   *
   * @default "medium"
   * @type {FieldSize}
   */
  size?: FieldSize;
  /**
   * Color.
   *
   * @default "primary"
   * @type {FieldAccentColor}
   */
  color?: FieldAccentColor;
  /**
   * Error.
   *
   * @default false
   * @type {boolean}
   */
  error?: boolean;
  /**
   * Helper Text.
   *
   * @default undefined
   * @type {ReactNode}
   */
  helperText?: ReactNode;
  /**
   * Disabled.
   *
   * @default false
   * @type {boolean}
   */
  disabled?: boolean;
  /**
   * Full Width.
   *
   * @default false
   * @type {boolean}
   */
  fullWidth?: boolean;
  /**
   * Start Adornment.
   *
   * @default undefined
   * @type {ReactNode}
   */
  startAdornment?: ReactNode;
  /**
   * End Adornment.
   *
   * @default undefined
   * @type {ReactNode}
   */
  endAdornment?: ReactNode;
  /**
   * `<label for>` only works for real form controls, so a wrapper whose control is a `div[role="combobox"]` (Select) passes `false` and points at `${id}-label` with `aria-labelledby` instead.
   *
   * @default undefined
   * @type {string | false}
   */
  htmlFor?: string | false;
  /**
   * Applied to the bordered control box — Autocomplete anchors its popup on it.
   *
   * @default undefined
   * @type {*}
   */
  controlProps?: HTMLAttributes<HTMLDivElement> & { ref?: Ref<HTMLDivElement> };
  /**
   * Class Name.
   *
   * @default undefined
   * @type {string}
   */
  className?: string;
  /**
   * Children.
   *
   * @default undefined
   * @type {ReactNode}
   */
  children: ReactNode;
}

/**
 * The shared shell behind TextField, Select and Autocomplete: label row,
 * bordered control box with optional adornments, and helper text.
 *
 * Internal on purpose — it is not exported from the package. It exists to stop
 * the three components from re-implementing (and slowly disagreeing about)
 * focus rings, error colours and label spacing, not to become a public
 * layout primitive. Its styling counterpart is the `field.shell` SCSS mixin.
 */
export function Field({
  block,
  id,
  label,
  hideLabel = false,
  required = false,
  size = "medium",
  color = "primary",
  error = false,
  helperText,
  disabled = false,
  fullWidth = false,
  startAdornment,
  endAdornment,
  htmlFor,
  controlProps,
  className,
  children,
}: FieldProps) {
  const helperId = helperText ? `${id}-helper` : undefined;
  const labelId = label ? `${id}-label` : undefined;

  const classes = [
    "okkly-component",
    block,
    color !== "primary" && `${block}--color-${color}`,
    size !== "medium" && `${block}--${size}`,
    error && `${block}--error`,
    disabled && `${block}--disabled`,
    fullWidth && `${block}--full-width`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const { className: controlClassName, ...restControlProps } = controlProps ?? {};

  return (
    <div className={classes}>
      {label && (
        <label
          id={labelId}
          htmlFor={htmlFor === false ? undefined : (htmlFor ?? id)}
          className={`${block}__label${hideLabel ? ` ${block}__label--hidden` : ""}`}
        >
          {label}
          {required && (
            <span className={`${block}__required`} aria-hidden="true">
              *
            </span>
          )}
        </label>
      )}

      <div
        className={[`${block}__control`, controlClassName].filter(Boolean).join(" ")}
        {...restControlProps}
      >
        {startAdornment && <span className={`${block}__adornment`}>{startAdornment}</span>}
        {children}
        {endAdornment && <span className={`${block}__adornment`}>{endAdornment}</span>}
      </div>

      {helperText && (
        <span id={helperId} className={`${block}__helper`}>
          {helperText}
        </span>
      )}
    </div>
  );
}

/** Ids `Field` derives from the control id, so callers can wire aria attributes to them. */
export function getFieldIds(id: string, hasLabel: boolean, hasHelperText: boolean) {
  return {
    labelId: hasLabel ? `${id}-label` : undefined,
    helperId: hasHelperText ? `${id}-helper` : undefined,
  };
}
