// packages/vue/src/components/Field/Field.vue
<script lang="ts">
export type FieldSize = "small" | "medium" | "large";
export type FieldColor = "primary" | "dante";
/**
 * Every accent tint a `Field`-shell control can take. Broader than
 * `FieldColor`, which is what Select/Autocomplete/DateField/TimeField/etc.
 * still expose publicly — TextField is the one consumer that opts into the
 * full accent set.
 */
export type FieldAccentColor = FieldColor | "secondary" | "violet" | "ember" | "ice" | "contrast";

/**
 * Props mirror `@okkly/react`'s internal `<Field>` name-for-name. Deliberate
 * differences, because Vue has no `ReactNode`: `label`, `helperText`,
 * `startAdornment` and `endAdornment` arrive as the `label`, `helper-text`,
 * `start-adornment` and `end-adornment` slots, and `children` is the default
 * slot. `controlProps` and `className` are dropped — nothing yet needs to
 * reach the inner control box, and Vue merges a consumer's `class` onto the
 * root on its own.
 *
 * Internal on purpose — not exported from the package. It is the shared shell
 * TextField (and, later, Select/Autocomplete) render inside; its styling
 * counterpart is the `field.shell` SCSS mixin, included by each consumer's own
 * stylesheet under its own BEM block.
 */
export interface FieldProps {
  /**
   * BEM block the emitted classes are namespaced under, e.g. `"okkly-text-field"`. Each consumer keeps its own block so its public class names stay exactly what they were.
   *
   * @default undefined
   */
  block: string;
  /**
   * Id of the control this field wraps; the label's `for` and the helper id derive from it.
   *
   * @default undefined
   */
  id: string;
  /**
   * Hide Label.
   *
   * @default false
   */
  hideLabel?: boolean;
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   */
  required?: boolean;
  /**
   * Size.
   *
   * @default "medium"
   */
  size?: FieldSize;
  /**
   * Tints the focus ring/glow. `dante` is a rare, deliberate accent moment;
   * the rest are for matching a field to surrounding brand/section color.
   *
   * @default "primary"
   */
  color?: FieldAccentColor;
  /**
   * Error.
   *
   * @default false
   */
  error?: boolean;
  /**
   * Disabled.
   *
   * @default false
   */
  disabled?: boolean;
  /**
   * Full Width.
   *
   * @default false
   */
  fullWidth?: boolean;
  /**
   * `<label for>` only works for real form controls, so a wrapper whose control is a `div[role="combobox"]` passes `false` and points at `${id}-label` with `aria-labelledby` instead.
   *
   * @default undefined
   */
  htmlFor?: string | false;
}

/** Ids `Field` derives from the control id, so callers can wire aria attributes to them. */
export function getFieldIds(id: string, hasLabel: boolean, hasHelperText: boolean) {
  return {
    labelId: hasLabel ? `${id}-label` : undefined,
    helperId: hasHelperText ? `${id}-helper` : undefined,
  };
}
</script>

<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(defineProps<FieldProps>(), {
  hideLabel: false,
  required: false,
  size: "medium",
  color: "primary",
  error: false,
  disabled: false,
  fullWidth: false,
  htmlFor: undefined,
});

const slots = defineSlots<{
  /** Content of the field — the control itself. */
  default?: () => unknown;
  /** Label. */
  label?: () => unknown;
  /** Helper text below the field. */
  "helper-text"?: () => unknown;
  /** Content rendered inside the border, before the control. */
  "start-adornment"?: () => unknown;
  /** Content rendered inside the border, after the control. */
  "end-adornment"?: () => unknown;
}>();

const hasLabel = computed(() => !!slots.label);
const hasHelperText = computed(() => !!slots["helper-text"]);
const ids = computed(() => getFieldIds(props.id, hasLabel.value, hasHelperText.value));

const labelFor = computed(() =>
  props.htmlFor === false ? undefined : (props.htmlFor ?? props.id),
);

const classes = computed(() =>
  [
    "okkly-component",
    props.block,
    props.color !== "primary" && `${props.block}--color-${props.color}`,
    props.size !== "medium" && `${props.block}--${props.size}`,
    props.error && `${props.block}--error`,
    props.disabled && `${props.block}--disabled`,
    props.fullWidth && `${props.block}--full-width`,
  ]
    .filter(Boolean)
    .join(" "),
);

const labelClasses = computed(() =>
  [`${props.block}__label`, props.hideLabel && `${props.block}__label--hidden`]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <div :class="classes">
    <label v-if="hasLabel" :id="ids.labelId" :for="labelFor" :class="labelClasses">
      <slot name="label" />
      <span v-if="required" :class="`${block}__required`" aria-hidden="true">*</span>
    </label>

    <div :class="`${block}__control`">
      <span v-if="slots['start-adornment']" :class="`${block}__adornment`">
        <slot name="start-adornment" />
      </span>
      <slot />
      <span v-if="slots['end-adornment']" :class="`${block}__adornment`">
        <slot name="end-adornment" />
      </span>
    </div>

    <span v-if="hasHelperText" :id="ids.helperId" :class="`${block}__helper`">
      <slot name="helper-text" />
    </span>
  </div>
</template>

// packages/react/src/components/Field/Field.tsx
"use client";

import type { HTMLAttributes, Ref, ReactNode } from "react";

export type FieldSize = "small" | "medium" | "large";
export type FieldColor = "primary" | "dante";
/**
 * Every accent tint a `Field`-shell control can take. Broader than
 * `FieldColor`, which is what Select/Autocomplete/DateField/TimeField/etc.
 * still expose publicly — TextField is the one consumer that opts into the
 * full accent set.
 */
export type FieldAccentColor = FieldColor | "secondary" | "violet" | "ember" | "ice" | "contrast";

export interface FieldProps {
  /**
   * BEM block the emitted classes are namespaced under, e.g. `"okkly-select"`. Each consumer keeps its own block so its public class names — the ones apps target in overrides — stay exactly what they were.
   *
   * @default undefined
   * @type {string}
   */
  block: string;
  /**
   * Id of the control this field wraps; the label's `for` and the helper id derive from it.
   *
   * @default undefined
   * @type {string}
   */
  id: string;
  /**
   * Label.
   *
   * @default undefined
   * @type {ReactNode}
   */
  label?: ReactNode;
  /**
   * Hide Label.
   *
   * @default false
   * @type {boolean}
   */
  hideLabel?: boolean;
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   * @type {boolean}
   */
  required?: boolean;
  /**
   * Size.
   *
   * @default "medium"
   * @type {FieldSize}
   */
  size?: FieldSize;
  /**
   * Color.
   *
   * @default "primary"
   * @type {FieldAccentColor}
   */
  color?: FieldAccentColor;
  /**
   * Error.
   *
   * @default false
   * @type {boolean}
   */
  error?: boolean;
  /**
   * Helper Text.
   *
   * @default undefined
   * @type {ReactNode}
   */
  helperText?: ReactNode;
  /**
   * Disabled.
   *
   * @default false
   * @type {boolean}
   */
  disabled?: boolean;
  /**
   * Full Width.
   *
   * @default false
   * @type {boolean}
   */
  fullWidth?: boolean;
  /**
   * Start Adornment.
   *
   * @default undefined
   * @type {ReactNode}
   */
  startAdornment?: ReactNode;
  /**
   * End Adornment.
   *
   * @default undefined
   * @type {ReactNode}
   */
  endAdornment?: ReactNode;
  /**
   * `<label for>` only works for real form controls, so a wrapper whose control is a `div[role="combobox"]` (Select) passes `false` and points at `${id}-label` with `aria-labelledby` instead.
   *
   * @default undefined
   * @type {string | false}
   */
  htmlFor?: string | false;
  /**
   * Applied to the bordered control box — Autocomplete anchors its popup on it.
   *
   * @default undefined
   * @type {*}
   */
  controlProps?: HTMLAttributes<HTMLDivElement> & { ref?: Ref<HTMLDivElement> };
  /**
   * Class Name.
   *
   * @default undefined
   * @type {string}
   */
  className?: string;
  /**
   * Children.
   *
   * @default undefined
   * @type {ReactNode}
   */
  children: ReactNode;
}

/**
 * The shared shell behind TextField, Select and Autocomplete: label row,
 * bordered control box with optional adornments, and helper text.
 *
 * Internal on purpose — it is not exported from the package. It exists to stop
 * the three components from re-implementing (and slowly disagreeing about)
 * focus rings, error colours and label spacing, not to become a public
 * layout primitive. Its styling counterpart is the `field.shell` SCSS mixin.
 */
export function Field({
  block,
  id,
  label,
  hideLabel = false,
  required = false,
  size = "medium",
  color = "primary",
  error = false,
  helperText,
  disabled = false,
  fullWidth = false,
  startAdornment,
  endAdornment,
  htmlFor,
  controlProps,
  className,
  children,
}: FieldProps) {
  const helperId = helperText ? `${id}-helper` : undefined;
  const labelId = label ? `${id}-label` : undefined;

  const classes = [
    "okkly-component",
    block,
    color !== "primary" && `${block}--color-${color}`,
    size !== "medium" && `${block}--${size}`,
    error && `${block}--error`,
    disabled && `${block}--disabled`,
    fullWidth && `${block}--full-width`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const { className: controlClassName, ...restControlProps } = controlProps ?? {};

  return (
    <div className={classes}>
      {label && (
        <label
          id={labelId}
          htmlFor={htmlFor === false ? undefined : (htmlFor ?? id)}
          className={`${block}__label${hideLabel ? ` ${block}__label--hidden` : ""}`}
        >
          {label}
          {required && (
            <span className={`${block}__required`} aria-hidden="true">
              *
            </span>
          )}
        </label>
      )}

      <div
        className={[`${block}__control`, controlClassName].filter(Boolean).join(" ")}
        {...restControlProps}
      >
        {startAdornment && <span className={`${block}__adornment`}>{startAdornment}</span>}
        {children}
        {endAdornment && <span className={`${block}__adornment`}>{endAdornment}</span>}
      </div>

      {helperText && (
        <span id={helperId} className={`${block}__helper`}>
          {helperText}
        </span>
      )}
    </div>
  );
}

/** Ids `Field` derives from the control id, so callers can wire aria attributes to them. */
export function getFieldIds(id: string, hasLabel: boolean, hasHelperText: boolean) {
  return {
    labelId: hasLabel ? `${id}-label` : undefined,
    helperId: hasHelperText ? `${id}-helper` : undefined,
  };
}
