// packages/vue/src/components/Rating/Rating.vue
<script lang="ts">
function defaultGetLabelText(value: number): string {
  return `${value} Star${value !== 1 ? "s" : ""}`;
}

function starKind(displayValue: number, index: number): "full" | "half" | "empty" {
  const position = index + 1;
  if (displayValue >= position) return "full";
  if (displayValue >= position - 0.5) return "half";
  return "empty";
}

function valueFromPointer(event: MouseEvent, index: number, precision: 0.5 | 1): number {
  if (precision === 1) return index + 1;
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  const ratio = (event.clientX - rect.left) / rect.width;
  return ratio <= 0.5 ? index + 0.5 : index + 1;
}
</script>

<script setup lang="ts">
import { computed, ref } from "vue";
import "@okkly/design-system/components/Rating/Rating.scss";
import RatingGlyph from "./RatingGlyph.vue";
import type { RatingProps } from "./Rating.types";

const props = withDefaults(defineProps<RatingProps>(), {
  defaultValue: null,
  max: 5,
  precision: 0.5,
  size: "medium",
  color: "warning",
  icon: "star",
  readOnly: false,
  disabled: false,
  name: undefined,
  getLabelText: defaultGetLabelText,
});

const slots = defineSlots<{
  /** Custom filled glyph, overriding the built-in `"star"`/`"heart"` shape. */
  icon?: () => unknown;
  /** Trailing summary (e.g. "4.8 · 128 reviews"). */
  label?: () => unknown;
}>();

// Unlike React's manual `value !== undefined ? value : internalValue` split,
// `model.value` already resolves controlled vs. uncontrolled — `undefined`
// means genuinely unbound, so it's the only case that falls back to
// `defaultValue`.
const model = defineModel<number | null>();
const resolvedValue = computed<number | null>(() =>
  model.value !== undefined ? model.value : props.defaultValue,
);

const hoverValue = ref<number | null>(null);
const displayValue = computed(() => hoverValue.value ?? resolvedValue.value ?? 0);

function commit(next: number | null) {
  model.value = next;
}

function handleItemClick(event: MouseEvent, index: number) {
  if (props.readOnly || props.disabled) return;
  const next = valueFromPointer(event, index, props.precision);
  if (next === resolvedValue.value) commit(null);
  else commit(next);
}

function handleItemMove(event: MouseEvent, index: number) {
  if (props.readOnly || props.disabled) return;
  hoverValue.value = valueFromPointer(event, index, props.precision);
}

function handleKeyDown(event: KeyboardEvent) {
  if (props.readOnly || props.disabled) return;
  const step = props.precision;
  const base = resolvedValue.value ?? 0;

  if (event.key === "ArrowRight" || event.key === "ArrowUp") {
    event.preventDefault();
    commit(Math.min(props.max, base + step));
  } else if (event.key === "ArrowLeft" || event.key === "ArrowDown") {
    event.preventDefault();
    commit(Math.max(0, base - step) || null);
  }
}

const stars = computed(() =>
  Array.from({ length: props.max }, (_, index) => ({
    index,
    kind: starKind(displayValue.value, index),
    label: props.getLabelText(index + 1),
  })),
);

const interactive = computed(() => !props.readOnly && !props.disabled);

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-rating",
    props.color !== "warning" && `okkly-rating--color-${props.color}`,
    props.size !== "medium" && `okkly-rating--${props.size}`,
    props.readOnly && "okkly-rating--read-only",
    props.disabled && "okkly-rating--disabled",
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <span
    :class="classes"
    :role="interactive ? 'radiogroup' : 'img'"
    :aria-label="!interactive ? `${displayValue} of ${max}` : undefined"
    @mouseleave="hoverValue = null"
  >
    <span class="okkly-rating__stars">
      <template v-for="star in stars" :key="star.index">
        <span v-if="!interactive" class="okkly-rating__item" aria-hidden="true">
          <RatingGlyph v-if="slots.icon" :kind="star.kind" :glyph="icon"
            ><slot name="icon"
          /></RatingGlyph>
          <RatingGlyph v-else :kind="star.kind" :glyph="icon" />
        </span>
        <button
          v-else
          type="button"
          class="okkly-rating__item"
          :name="name"
          :aria-label="star.label"
          @click="handleItemClick($event, star.index)"
          @mousemove="handleItemMove($event, star.index)"
          @keydown="handleKeyDown"
        >
          <RatingGlyph v-if="slots.icon" :kind="star.kind" :glyph="icon"
            ><slot name="icon"
          /></RatingGlyph>
          <RatingGlyph v-else :kind="star.kind" :glyph="icon" />
        </button>
      </template>
    </span>
    <span v-if="slots.label" class="okkly-rating__label"><slot name="label" /></span>
  </span>
</template>

// packages/react/src/components/Rating/Rating.tsx
"use client";

import {
  forwardRef,
  useState,
  type KeyboardEvent,
  type MouseEvent,
  type ReactNode,
  type SyntheticEvent,
} from "react";
import "@okkly/design-system/components/Rating/Rating.scss";
import type { RatingIcon, RatingPrecision, RatingProps } from "./Rating.types";

const StarOutline = () => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinejoin="round"
  >
    <path d="M12 2.5l2.93 5.94 6.56.95-4.75 4.63 1.12 6.54L12 17.77l-5.86 3.08 1.12-6.54-4.75-4.63 6.56-.95L12 2.5z" />
  </svg>
);

const StarFilled = () => (
  <svg viewBox="0 0 24 24" fill="currentColor" stroke="none">
    <path d="M12 2.5l2.93 5.94 6.56.95-4.75 4.63 1.12 6.54L12 17.77l-5.86 3.08 1.12-6.54-4.75-4.63 6.56-.95L12 2.5z" />
  </svg>
);

const HeartOutline = () => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinejoin="round"
  >
    <path d="M12 21s-6.5-4.35-9-8.35C1.5 10.5 2.5 6.5 6 5.5c2-.6 4 .5 6 2.5 2-2 4-3.1 6-2.5 3.5 1 4.5 5 3 7.15C18.5 16.65 12 21 12 21z" />
  </svg>
);

const HeartFilled = () => (
  <svg viewBox="0 0 24 24" fill="currentColor" stroke="none">
    <path d="M12 21s-6.5-4.35-9-8.35C1.5 10.5 2.5 6.5 6 5.5c2-.6 4 .5 6 2.5 2-2 4-3.1 6-2.5 3.5 1 4.5 5 3 7.15C18.5 16.65 12 21 12 21z" />
  </svg>
);

function defaultGetLabelText(value: number): string {
  return `${value} Star${value !== 1 ? "s" : ""}`;
}

function starKind(displayValue: number, index: number): "full" | "half" | "empty" {
  const position = index + 1;
  if (displayValue >= position) return "full";
  if (displayValue >= position - 0.5) return "half";
  return "empty";
}

function valueFromPointer(
  event: MouseEvent<HTMLButtonElement>,
  index: number,
  precision: RatingPrecision,
): number {
  if (precision === 1) return index + 1;
  const rect = event.currentTarget.getBoundingClientRect();
  const ratio = (event.clientX - rect.left) / rect.width;
  return ratio <= 0.5 ? index + 0.5 : index + 1;
}

export const Rating = forwardRef<HTMLSpanElement, RatingProps>(function Rating(
  {
    value,
    defaultValue = null,
    onChange,
    max = 5,
    precision = 0.5,
    size = "medium",
    color = "warning",
    icon = "star",
    readOnly = false,
    disabled = false,
    label,
    name,
    getLabelText = defaultGetLabelText,
    className,
  },
  forwardedRef,
) {
  const [internalValue, setInternalValue] = useState<number | null>(defaultValue);
  const [hoverValue, setHoverValue] = useState<number | null>(null);

  const isControlled = value !== undefined;
  const currentValue = isControlled ? value : internalValue;
  const displayValue = hoverValue ?? currentValue ?? 0;

  const commit = (event: SyntheticEvent, next: number | null) => {
    if (!isControlled) setInternalValue(next);
    onChange?.(event, next);
  };

  const handleItemClick = (event: MouseEvent<HTMLButtonElement>, index: number) => {
    if (readOnly || disabled) return;
    const next = valueFromPointer(event, index, precision);
    if (next === currentValue) commit(event, null);
    else commit(event, next);
  };

  const handleItemMove = (event: MouseEvent<HTMLButtonElement>, index: number) => {
    if (readOnly || disabled) return;
    setHoverValue(valueFromPointer(event, index, precision));
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    if (readOnly || disabled) return;
    const step = precision;
    const base = currentValue ?? 0;

    if (event.key === "ArrowRight" || event.key === "ArrowUp") {
      event.preventDefault();
      commit(event, Math.min(max, base + step));
    } else if (event.key === "ArrowLeft" || event.key === "ArrowDown") {
      event.preventDefault();
      commit(event, Math.max(0, base - step) || null);
    }
  };

  const renderBuiltInIcon = (kind: "full" | "half" | "empty", glyph: RatingIcon) => {
    const Outline = glyph === "heart" ? HeartOutline : StarOutline;
    const Filled = glyph === "heart" ? HeartFilled : StarFilled;

    if (kind === "full") {
      return (
        <span className="okkly-rating__icon okkly-rating__icon--full" aria-hidden="true">
          <Filled />
        </span>
      );
    }

    if (kind === "half") {
      return (
        <span className="okkly-rating__icon okkly-rating__icon--half" aria-hidden="true">
          <Outline />
          <span className="okkly-rating__icon-fill">
            <Filled />
          </span>
        </span>
      );
    }

    return (
      <span className="okkly-rating__icon" aria-hidden="true">
        <Outline />
      </span>
    );
  };

  const renderCustomIcon = (kind: "full" | "half" | "empty", customIcon: ReactNode) => {
    if (kind === "full") {
      return (
        <span className="okkly-rating__icon okkly-rating__icon--full" aria-hidden="true">
          {customIcon}
        </span>
      );
    }

    if (kind === "half") {
      return (
        <span className="okkly-rating__icon okkly-rating__icon--half" aria-hidden="true">
          {customIcon}
          <span className="okkly-rating__icon-fill">{customIcon}</span>
        </span>
      );
    }

    return (
      <span className="okkly-rating__icon" aria-hidden="true">
        {customIcon}
      </span>
    );
  };

  const isBuiltInGlyph = (glyph: RatingIcon | ReactNode): glyph is RatingIcon =>
    glyph === "star" || glyph === "heart";

  const renderIcon = (kind: "full" | "half" | "empty") => {
    if (isBuiltInGlyph(icon)) return renderBuiltInIcon(kind, icon);
    return renderCustomIcon(kind, icon);
  };

  const classes = [
    "okkly-component",
    "okkly-rating",
    color !== "warning" && `okkly-rating--color-${color}`,
    size !== "medium" && `okkly-rating--${size}`,
    readOnly && "okkly-rating--read-only",
    disabled && "okkly-rating--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const interactive = !readOnly && !disabled;

  return (
    <span
      ref={forwardedRef}
      className={classes}
      role={interactive ? "radiogroup" : "img"}
      aria-label={interactive ? undefined : `${displayValue} of ${max}`}
      onMouseLeave={() => setHoverValue(null)}
    >
      <span className="okkly-rating__stars">
        {Array.from({ length: max }, (_, index) => {
          const kind = starKind(displayValue, index);
          const itemValue = index + 1;

          if (!interactive) {
            return (
              <span key={index} className="okkly-rating__item" aria-hidden="true">
                {renderIcon(kind)}
              </span>
            );
          }

          return (
            <button
              key={index}
              type="button"
              className="okkly-rating__item"
              name={name}
              aria-label={getLabelText(itemValue)}
              onClick={(event) => handleItemClick(event, index)}
              onMouseMove={(event) => handleItemMove(event, index)}
              onKeyDown={(event) => handleKeyDown(event)}
            >
              {renderIcon(kind)}
            </button>
          );
        })}
      </span>
      {label && <span className="okkly-rating__label">{label}</span>}
    </span>
  );
});
