// packages/react/src/components/Slider/Slider.tsx
"use client";

import { forwardRef, useMemo, useState } from "react";
import { useSlider, valueToPercent } from "@okkly/react-hooks";
import "@okkly/design-system/components/Slider/Slider.scss";
import type { SliderProps } from "./Slider.types";

function isRangeValue(value: number | number[] | undefined): value is number[] {
  return Array.isArray(value);
}

function resolveInitialValue(
  isRange: boolean,
  min: number,
  max: number,
  defaultValue?: number | number[],
): number | number[] {
  if (defaultValue !== undefined) return defaultValue;
  return isRange ? [min + (max - min) * 0.25, min + (max - min) * 0.75] : min;
}

function formatValueLabel(value: number): string {
  return String(value);
}

export const Slider = forwardRef<HTMLDivElement, SliderProps>(function Slider(
  {
    value,
    defaultValue,
    onChange,
    onChangeCommitted,
    min = 0,
    max = 100,
    step = 1,
    marks = false,
    orientation = "horizontal",
    disabled = false,
    color = "primary",
    size = "medium",
    valueLabelDisplay = "off",
    discrete = false,
    shiftStep,
    getAriaLabel,
    getAriaValueText,
    track = "normal",
    valueLabelFormat = formatValueLabel,
    className,
    "aria-label": ariaLabel,
    ...rest
  },
  forwardedRef,
) {
  const isRange = isRangeValue(value) || isRangeValue(defaultValue);
  const [internalValue, setInternalValue] = useState<number | number[]>(() =>
    resolveInitialValue(isRange, min, max, defaultValue),
  );

  const isControlled = value !== undefined;
  const currentValue = isControlled ? value : internalValue;

  const handleChange = (next: number | number[]) => {
    if (!isControlled) setInternalValue(next);
    onChange?.(new Event("change") as Event, next);
  };

  const handleCommit = (next: number | number[]) => {
    onChangeCommitted?.(new Event("change") as Event, next);
  };

  const slider = useSlider({
    value: currentValue ?? (isRange ? [min, max] : min),
    min,
    max,
    step,
    discrete,
    shiftStep,
    disabled,
    marks,
    orientation,
    label: ariaLabel,
    getAriaLabel,
    getAriaValueText,
    onChange: handleChange,
    onCommit: handleCommit,
  });

  const {
    values,
    isDragging,
    activeThumbIndex,
    focusedThumbIndex,
    marksList,
    isMarkActive,
    valueToPercent: toPercent,
    getRootProps,
    getRailProps,
    getTrackProps,
    getThumbContainerProps,
    getThumbInputProps,
    getMarkProps,
    getMarkLabelProps,
  } = slider;

  const rootProps = getRootProps();
  const trackProps = getTrackProps();

  const invertedTracks = useMemo(() => {
    if (track !== "inverted") return null;

    if (!slider.isRange) {
      const start = toPercent(values[0] ?? min);
      return [{ offset: start, length: 100 - start }];
    }

    const lo = Math.min(...values);
    const hi = Math.max(...values);
    return [
      { offset: 0, length: toPercent(lo) },
      { offset: toPercent(hi), length: 100 - toPercent(hi) },
    ];
  }, [max, min, slider.isRange, toPercent, track, values]);

  const showValueLabel = (index: number) => {
    if (valueLabelDisplay === "off") return false;
    if (valueLabelDisplay === "on") return true;
    return isDragging || activeThumbIndex === index || focusedThumbIndex === index;
  };

  const classes = [
    "okkly-component",
    "okkly-slider",
    size !== "medium" && `okkly-slider--${size}`,
    color !== "primary" && `okkly-slider--color-${color}`,
    orientation === "vertical" && "okkly-slider--vertical",
    disabled && "okkly-slider--disabled",
    track === "inverted" && "okkly-slider--track-inverted",
    track === "none" && "okkly-slider--track-none",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const axis = orientation === "vertical" ? "bottom" : "left";
  const axisSize = orientation === "vertical" ? "height" : "width";

  const setRootRef = (node: HTMLDivElement | null) => {
    rootProps.ref.current = node;
    if (typeof forwardedRef === "function") forwardedRef(node);
    else if (forwardedRef) forwardedRef.current = node;
  };

  return (
    <div
      {...rest}
      {...rootProps}
      ref={setRootRef}
      className={classes}
      aria-disabled={disabled || undefined}
    >
      <div className="okkly-slider__rail" {...getRailProps()} />

      {track === "normal" && <div className="okkly-slider__track" {...trackProps} />}

      {invertedTracks?.map((segment, index) => (
        <div
          key={`inverted-${index}`}
          className="okkly-slider__track-inverted"
          role="presentation"
          aria-hidden
          style={{
            [axis]: `${segment.offset}%`,
            [axisSize]: `${segment.length}%`,
          }}
        />
      ))}

      {marksList.length > 0 && (
        <div className="okkly-slider__marks">
          {marksList.map((mark) => (
            <div key={mark.value}>
              <div
                className={[
                  "okkly-slider__mark",
                  isMarkActive(mark.value) && "okkly-slider__mark--active",
                ]
                  .filter(Boolean)
                  .join(" ")}
                {...getMarkProps(mark)}
              />
              {mark.label && (
                <span className="okkly-slider__mark-label" {...getMarkLabelProps(mark)}>
                  {mark.label}
                </span>
              )}
            </div>
          ))}
        </div>
      )}

      {values.map((thumbValue, index) => {
        const thumbContainerProps = getThumbContainerProps(index, thumbValue);
        const inputProps = getThumbInputProps(index, thumbValue);

        return (
          <div
            key={index}
            className={[
              "okkly-slider__thumb",
              (activeThumbIndex === index || focusedThumbIndex === index) &&
                "okkly-slider__thumb--active",
            ]
              .filter(Boolean)
              .join(" ")}
            {...thumbContainerProps}
          >
            {showValueLabel(index) && (
              <span className="okkly-slider__value-label">
                {valueLabelFormat(thumbValue, index)}
              </span>
            )}
            <span className="okkly-slider__handle" aria-hidden="true" />
            <input className="okkly-slider__input" {...inputProps} />
          </div>
        );
      })}
    </div>
  );
});

export { valueToPercent };

// packages/vue/src/components/Slider/Slider.vue
<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from "vue";
import "@okkly/design-system/components/Slider/Slider.scss";
import { useSlider } from "@okkly/vue-composables";
import type { SliderProps } from "./Slider.types";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SliderProps>(), {
  defaultValue: undefined,
  min: 0,
  max: 100,
  step: 1,
  marks: false,
  orientation: "horizontal",
  disabled: false,
  color: "primary",
  size: "medium",
  valueLabelDisplay: "off",
  discrete: false,
  shiftStep: undefined,
  getAriaLabel: undefined,
  getAriaValueText: undefined,
  track: "normal",
  valueLabelFormat: (value: number) => String(value),
});

const emit = defineEmits<{
  changeCommitted: [value: number | number[]];
}>();

const model = defineModel<number | number[]>();
// `defaultValue` is only ever read here, never written into `model` — an
// eager write would emit `update:modelValue` on mount (setting `model.value`
// always emits, controlled or not), which React's lazy `useState` initializer
// never does since nothing calls `onChange` before the user acts.
const resolvedValue = computed(() =>
  model.value !== undefined
    ? model.value
    : props.defaultValue !== undefined
      ? props.defaultValue
      : props.min,
);

const attrs = useAttrs();
// `aria-label` doesn't land on the root — React reads it off the props and
// hands it to the hook, which applies it per-thumb instead (see the `label`
// option below), so it's pulled out of the fallthrough rest here too.
const restAttrs = computed(() => {
  const { class: _class, "aria-label": _ariaLabel, ...rest } = attrs;
  return rest;
});

const root = useTemplateRef<HTMLDivElement>("root");

const slider = useSlider(root, () => ({
  value: resolvedValue.value,
  min: props.min,
  max: props.max,
  step: props.step,
  discrete: props.discrete,
  shiftStep: props.shiftStep,
  disabled: props.disabled,
  marks: props.marks,
  orientation: props.orientation,
  label: attrs["aria-label"] as string | undefined,
  getAriaLabel: props.getAriaLabel,
  getAriaValueText: props.getAriaValueText,
  onChange: (next) => {
    model.value = next;
  },
  onCommit: (next) => {
    emit("changeCommitted", next);
  },
}));

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-slider",
    props.size !== "medium" && `okkly-slider--${props.size}`,
    props.color !== "primary" && `okkly-slider--color-${props.color}`,
    props.orientation === "vertical" && "okkly-slider--vertical",
    props.disabled && "okkly-slider--disabled",
    props.track === "inverted" && "okkly-slider--track-inverted",
    props.track === "none" && "okkly-slider--track-none",
    attrs.class,
  ]
    .filter(Boolean)
    .join(" "),
);

const axisPosition = computed(() => (props.orientation === "vertical" ? "bottom" : "left"));
const axisSize = computed(() => (props.orientation === "vertical" ? "height" : "width"));

const invertedTracks = computed(() => {
  if (props.track !== "inverted") return null;

  const values = slider.values.value;
  const toPercent = slider.valueToPercent;

  if (!slider.isRange.value) {
    const start = toPercent(values[0] ?? props.min);
    return [{ offset: start, length: 100 - start }];
  }

  const lo = Math.min(...values);
  const hi = Math.max(...values);
  return [
    { offset: 0, length: toPercent(lo) },
    { offset: toPercent(hi), length: 100 - toPercent(hi) },
  ];
});

function showValueLabel(index: number) {
  if (props.valueLabelDisplay === "off") return false;
  if (props.valueLabelDisplay === "on") return true;
  return (
    slider.isDragging.value ||
    slider.activeThumbIndex.value === index ||
    slider.focusedThumbIndex.value === index
  );
}
</script>

<template>
  <div
    ref="root"
    v-bind="restAttrs"
    :class="classes"
    :style="slider.rootStyle.value"
    :aria-disabled="disabled || undefined"
    v-on="slider.rootEvents"
  >
    <div class="okkly-slider__rail" role="presentation" aria-hidden="true" />

    <div
      v-if="track === 'normal'"
      class="okkly-slider__track"
      role="presentation"
      aria-hidden="true"
      :style="slider.trackStyle.value"
    />

    <div
      v-for="(segment, index) in invertedTracks"
      :key="`inverted-${index}`"
      class="okkly-slider__track-inverted"
      role="presentation"
      aria-hidden="true"
      :style="{ [axisPosition]: `${segment.offset}%`, [axisSize]: `${segment.length}%` }"
    />

    <div v-if="slider.marksList.value.length > 0" class="okkly-slider__marks">
      <div v-for="mark in slider.marksList.value" :key="mark.value">
        <div
          :class="[
            'okkly-slider__mark',
            slider.isMarkActive(mark.value) && 'okkly-slider__mark--active',
          ]"
          :data-value="mark.value"
          aria-hidden="true"
          :style="slider.markStyle(mark)"
        />
        <span
          v-if="mark.label"
          class="okkly-slider__mark-label"
          :data-value="mark.value"
          aria-hidden="true"
          :style="slider.markLabelStyle(mark)"
          >{{ mark.label }}</span
        >
      </div>
    </div>

    <div
      v-for="(thumbValue, index) in slider.values.value"
      :key="index"
      class="okkly-slider__thumb"
      :class="{
        'okkly-slider__thumb--active':
          slider.activeThumbIndex.value === index || slider.focusedThumbIndex.value === index,
      }"
      :data-index="index"
      :style="slider.thumbStyle(index, thumbValue)"
    >
      <span v-if="showValueLabel(index)" class="okkly-slider__value-label">{{
        valueLabelFormat(thumbValue, index)
      }}</span>
      <span class="okkly-slider__handle" aria-hidden="true" />
      <input
        class="okkly-slider__input"
        v-bind="slider.thumbInputAttrs(index, thumbValue)"
        v-on="slider.thumbInputEvents"
      />
    </div>
  </div>
</template>
