// packages/react/src/playwright/fixtures/SwipeableDrawerFixtures.tsx
import { useState } from "react";
import { SwipeableDrawer } from "../../components/SwipeableDrawer/SwipeableDrawer";
import type { SwipeableDrawerProps } from "../../components/SwipeableDrawer/SwipeableDrawer.types";

type ControlledSwipeableDrawerProps = Omit<
  SwipeableDrawerProps,
  "open" | "onOpen" | "onClose" | "children"
>;

export function ControlledSwipeableDrawer({
  anchor = "left",
  ...props
}: ControlledSwipeableDrawerProps) {
  const [open, setOpen] = useState(false);
  const [opens, setOpens] = useState(0);
  const [closes, setCloses] = useState(0);

  return (
    <div>
      <span data-testid="opens">{opens}</span>
      <span data-testid="closes">{closes}</span>
      <SwipeableDrawer
        {...props}
        open={open}
        anchor={anchor}
        onOpen={() => {
          setOpen(true);
          setOpens((value) => value + 1);
        }}
        onClose={() => {
          setOpen(false);
          setCloses((value) => value + 1);
        }}
      >
        <div style={{ padding: 16, height: "100%" }}>Panel content</div>
      </SwipeableDrawer>
    </div>
  );
}

// packages/vue/src/playwright/fixtures/SwipeableDrawerFixtures.vue
<script setup lang="ts">
import { ref } from "vue";
import SwipeableDrawer from "../../components/SwipeableDrawer/SwipeableDrawer.vue";
import type { SwipeableDrawerProps } from "../../components/SwipeableDrawer/SwipeableDrawer.types";

type ControlledSwipeableDrawerProps = Omit<SwipeableDrawerProps, "open">;

withDefaults(defineProps<ControlledSwipeableDrawerProps>(), {
  anchor: "left",
});

const open = ref(false);
const opens = ref(0);
const closes = ref(0);

function handleOpen() {
  open.value = true;
  opens.value += 1;
}

function handleClose() {
  open.value = false;
  closes.value += 1;
}
</script>

<template>
  <div>
    <span data-testid="opens">{{ opens }}</span>
    <span data-testid="closes">{{ closes }}</span>
    <SwipeableDrawer v-bind="$props" :open="open" @open="handleOpen" @close="handleClose">
      <div style="padding: 16px; height: 100%">Panel content</div>
    </SwipeableDrawer>
  </div>
</template>
