// packages/angular/src/components/Progress/Progress.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  input,
  numberAttribute,
} from "@angular/core";

export type ProgressVariant = "determinate" | "indeterminate";
export type ProgressType = "linear" | "circular";
export type ProgressSize = "small" | "medium" | "large";
export type ProgressColor =
  "primary" | "dante" | "indigo" | "violet" | "ember" | "ice" | "success" | "warning" | "danger";

/**
 * Inputs mirror `@okkly/react`'s `<Progress>` name-for-name — `value`
 * (0–100), `variant`, `type`, `color`, `size`, `showLabel` — which follows
 * MUI's LinearProgress / CircularProgress APIs.
 *
 * Deliberate gaps: Angular Material splits this into `mat-progress-bar` and
 * `mat-progress-spinner` and calls the variant `mode`; this design keeps one
 * element with a `type` switch and React's `variant` name, and has no
 * `buffer`/`query` modes. The host is the `role="progressbar"` element and
 * carries no name of its own — pass `aria-label` or `aria-labelledby`.
 */
@Component({
  selector: "okkly-progress",
  changeDetection: ChangeDetectionStrategy.OnPush,
  // Every rule this renders lives in @okkly/design-system as a global BEM
  // class inside the `okkly` cascade layer; scoping attributes would only add
  // noise to the DOM.
  encapsulation: ViewEncapsulation.None,
  host: {
    class: "okkly-component okkly-progress",
    "[class]": "modifiers()",
    role: "progressbar",
    "aria-valuemin": "0",
    "aria-valuemax": "100",
    "[attr.aria-valuenow]": "isIndeterminate() ? null : clamped()",
  },
  templateUrl: "./Progress.html",
})
export class OkklyProgress {
  /**
   * Progress value, 0–100. Ignored when `variant="indeterminate"`.
   *
   * @default 0
   */
  readonly value = input(0, { transform: (value: unknown) => numberAttribute(value, 0) });
  /**
   * Known vs unknown duration.
   *
   * @default "determinate"
   */
  readonly variant = input<ProgressVariant>("determinate");
  /**
   * Linear bar or circular ring.
   *
   * @default "linear"
   */
  readonly type = input<ProgressType>("linear");
  /**
   * Accent or feedback tone.
   *
   * @default "primary"
   */
  readonly color = input<ProgressColor>("primary");
  /**
   * Track / ring thickness preset.
   *
   * @default "medium"
   */
  readonly size = input<ProgressSize>("medium");
  /**
   * Show the percentage inside a determinate circular ring.
   *
   * @default false
   */
  readonly showLabel = input(false, { transform: booleanAttribute });

  protected readonly clamped = computed(() => Math.min(100, Math.max(0, this.value())));
  protected readonly isIndeterminate = computed(() => this.variant() === "indeterminate");
  protected readonly percentLabel = computed(() => Math.round(this.clamped()));

  protected readonly ring = computed(() => {
    const size = this.size();
    const diameter = size === "small" ? 40 : size === "large" ? 72 : 56;
    const stroke = size === "small" ? 4 : size === "large" ? 6 : 5;
    const radius = diameter / 2 - stroke / 2;
    const circumference = radius * 2 * Math.PI;
    return {
      center: diameter / 2,
      radius,
      stroke,
      circumference,
      viewBox: `0 0 ${diameter} ${diameter}`,
      offset: this.isIndeterminate()
        ? circumference * 0.75
        : circumference - (this.clamped() / 100) * circumference,
    };
  });

  protected readonly modifiers = computed(() =>
    [
      `okkly-progress--${this.type()}`,
      this.isIndeterminate() && "okkly-progress--indeterminate",
      this.size() !== "medium" && `okkly-progress--${this.size()}`,
      this.color() !== "primary" && `okkly-progress--${this.color()}`,
    ]
      .filter(Boolean)
      .join(" "),
  );
}

// packages/vue/src/components/Progress/Progress.vue
<script setup lang="ts">
import { computed } from "vue";
import "@okkly/design-system/components/Progress/Progress.scss";
import type { ProgressProps } from "./Progress.types";

const props = withDefaults(defineProps<ProgressProps>(), {
  value: 0,
  variant: "determinate",
  type: "linear",
  color: "primary",
  size: "medium",
  showLabel: false,
});

const isIndeterminate = computed(() => props.variant === "indeterminate");
const clamped = computed(() => Math.min(100, Math.max(0, props.value)));

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-progress",
    `okkly-progress--${props.type}`,
    isIndeterminate.value && "okkly-progress--indeterminate",
    props.size !== "medium" && `okkly-progress--${props.size}`,
    props.color !== "primary" && `okkly-progress--${props.color}`,
  ]
    .filter(Boolean)
    .join(" "),
);

const diameter = computed(() => (props.size === "small" ? 40 : props.size === "large" ? 72 : 56));
const stroke = computed(() => (props.size === "small" ? 4 : props.size === "large" ? 6 : 5));
const radius = computed(() => diameter.value / 2 - stroke.value / 2);
const circumference = computed(() => radius.value * 2 * Math.PI);
const offset = computed(() =>
  isIndeterminate.value
    ? circumference.value * 0.75
    : circumference.value - (clamped.value / 100) * circumference.value,
);
</script>

<template>
  <div
    role="progressbar"
    :aria-valuenow="isIndeterminate ? undefined : clamped"
    :aria-valuemin="0"
    :aria-valuemax="100"
    :class="classes"
  >
    <div v-if="type === 'circular'" class="okkly-progress__circular">
      <svg class="okkly-progress__svg" :viewBox="`0 0 ${diameter} ${diameter}`">
        <circle
          class="okkly-progress__circle-track"
          :cx="diameter / 2"
          :cy="diameter / 2"
          :r="radius"
          fill="none"
          :stroke-width="stroke"
        />
        <circle
          class="okkly-progress__circle-bar"
          :cx="diameter / 2"
          :cy="diameter / 2"
          :r="radius"
          fill="none"
          :stroke-width="stroke"
          :stroke-dasharray="circumference"
          :stroke-dashoffset="offset"
        />
      </svg>
      <span v-if="showLabel && !isIndeterminate" class="okkly-progress__label"
        >{{ Math.round(clamped) }}%</span
      >
    </div>
    <div v-else class="okkly-progress__track">
      <div v-if="!isIndeterminate" class="okkly-progress__bar" :style="{ width: `${clamped}%` }" />
      <div v-else class="okkly-progress__bar" />
    </div>
  </div>
</template>
