// packages/angular/src/components/Spinner/Spinner.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  input,
  numberAttribute,
} from "@angular/core";

export type SpinnerSize = "small" | "medium" | "large";
export type SpinnerColor =
  "primary" | "dante" | "indigo" | "violet" | "ember" | "ice" | "success" | "warning" | "danger";

const SIZE_RADIUS: Record<SpinnerSize, number> = {
  small: 10,
  medium: 14,
  large: 20,
};

/**
 * Inputs mirror `@okkly/react`'s `<Spinner>` name-for-name — `size`, `color`,
 * `thickness` — which follows MUI's CircularProgress API in spirit. Angular
 * Material's `mat-spinner` is the precedent for the element selector.
 *
 * Deliberate gaps: always indeterminate (no `mode`/`value` — that is
 * `OkklyProgress`'s job), and the host's `aria-label` is an input aliased to
 * the attribute, so `<okkly-spinner aria-label="Loading projects">` replaces
 * the default "Loading" instead of competing with it.
 */
@Component({
  selector: "okkly-spinner",
  changeDetection: ChangeDetectionStrategy.OnPush,
  // Every rule this renders lives in @okkly/design-system as a global BEM
  // class inside the `okkly` cascade layer; scoping attributes would only add
  // noise to the DOM.
  encapsulation: ViewEncapsulation.None,
  host: {
    class: "okkly-component okkly-spinner",
    "[class]": "modifiers()",
    role: "status",
    "[attr.aria-label]": "ariaLabel()",
  },
  template: `
    <svg class="okkly-spinner__svg" [attr.viewBox]="geometry().viewBox">
      <circle
        class="okkly-spinner__track"
        [attr.cx]="geometry().radius"
        [attr.cy]="geometry().radius"
        [attr.r]="geometry().normalizedRadius"
        fill="none"
        [attr.stroke-width]="geometry().stroke"
      />
      <circle
        class="okkly-spinner__arc"
        [attr.cx]="geometry().radius"
        [attr.cy]="geometry().radius"
        [attr.r]="geometry().normalizedRadius"
        fill="none"
        [attr.stroke-width]="geometry().stroke"
        [attr.stroke-dasharray]="geometry().dashArray"
        [attr.stroke-dashoffset]="geometry().dashOffset"
      />
    </svg>
  `,
})
export class OkklySpinner {
  /**
   * Diameter preset.
   *
   * @default "medium"
   */
  readonly size = input<SpinnerSize>("medium");
  /**
   * Accent or feedback tone.
   *
   * @default "primary"
   */
  readonly color = input<SpinnerColor>("primary");
  /**
   * Ring stroke width in pixels at the preset's own size. Overrides the preset.
   *
   * @default undefined
   */
  readonly thickness = input<number | undefined, unknown>(undefined, {
    transform: (value: unknown) => (value == null ? undefined : numberAttribute(value)),
  });
  /**
   * Accessible name of the status region. Say what is loading.
   *
   * @default "Loading"
   */
  readonly ariaLabel = input("Loading", { alias: "aria-label" });

  protected readonly geometry = computed(() => {
    const radius = SIZE_RADIUS[this.size()];
    const stroke =
      this.thickness() ?? (this.size() === "small" ? 2.5 : this.size() === "large" ? 4 : 3);
    const normalizedRadius = radius - stroke / 2;
    const circumference = normalizedRadius * 2 * Math.PI;
    return {
      radius,
      stroke,
      normalizedRadius,
      viewBox: `0 0 ${radius * 2} ${radius * 2}`,
      dashArray: `${circumference * 0.25} ${circumference}`,
      dashOffset: circumference * 0.75,
    };
  });

  protected readonly modifiers = computed(() =>
    [
      this.size() !== "medium" && `okkly-spinner--${this.size()}`,
      this.color() !== "primary" && `okkly-spinner--${this.color()}`,
    ]
      .filter(Boolean)
      .join(" "),
  );
}

// packages/vue/src/components/Spinner/Spinner.vue
<script setup lang="ts">
import { computed } from "vue";
import "@okkly/design-system/components/Spinner/Spinner.scss";
import type { SpinnerProps } from "./Spinner.types";

const props = withDefaults(defineProps<SpinnerProps>(), {
  size: "medium",
  color: "primary",
  thickness: undefined,
});

const SIZE_RADIUS: Record<string, number> = { small: 10, medium: 14, large: 20 };

const radius = computed(() => SIZE_RADIUS[props.size]);
const stroke = computed(
  () => props.thickness ?? (props.size === "small" ? 2.5 : props.size === "large" ? 4 : 3),
);
const normalizedRadius = computed(() => radius.value - stroke.value / 2);
const circumference = computed(() => normalizedRadius.value * 2 * Math.PI);
const dashOffset = computed(() => circumference.value * 0.75);
const viewBox = computed(() => `0 0 ${radius.value * 2} ${radius.value * 2}`);
const dashArray = computed(() => `${circumference.value * 0.25} ${circumference.value}`);

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-spinner",
    props.size !== "medium" && `okkly-spinner--${props.size}`,
    props.color !== "primary" && `okkly-spinner--${props.color}`,
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <span role="status" aria-label="Loading" :class="classes">
    <svg class="okkly-spinner__svg" :viewBox="viewBox">
      <circle
        class="okkly-spinner__track"
        :cx="radius"
        :cy="radius"
        :r="normalizedRadius"
        fill="none"
        :stroke-width="stroke"
      />
      <circle
        class="okkly-spinner__arc"
        :cx="radius"
        :cy="radius"
        :r="normalizedRadius"
        fill="none"
        :stroke-width="stroke"
        :stroke-dasharray="dashArray"
        :stroke-dashoffset="dashOffset"
      />
    </svg>
  </span>
</template>
