// packages/react/src/components/RadioGroup/RadioGroup.tsx
"use client";

import { useId, useState } from "react";
import "@okkly/design-system/components/RadioGroup/RadioGroup.scss";

import { RadioGroupContext } from "./RadioGroupContext";
import type { RadioGroupProps } from "./RadioGroup.types";

/**
 * Groups `Radio` children via context — nest them directly rather than
 * passing an options array, matching MUI's RadioGroup composition pattern
 * (https://mui.com/material-ui/react-radio-button/#radio-group).
 */
export function RadioGroup({
  name,
  value,
  defaultValue,
  onChange,
  disabled = false,
  size = "medium",
  color = "primary",
  label,
  children,
  className,
}: RadioGroupProps) {
  const generatedName = useId();
  const [internalValue, setInternalValue] = useState(defaultValue);
  const currentValue = value ?? internalValue;

  const handleSelect = (next: string) => {
    if (value === undefined) setInternalValue(next);
    onChange?.(next);
  };

  const classes = ["okkly-component", "okkly-radio-group", className].filter(Boolean).join(" ");

  return (
    <RadioGroupContext.Provider
      value={{
        name: name ?? generatedName,
        value: currentValue,
        onSelect: handleSelect,
        disabled,
        size,
        color,
      }}
    >
      <div
        role="radiogroup"
        aria-label={typeof label === "string" ? label : undefined}
        className={classes}
      >
        {label && <span className="okkly-radio-group__label">{label}</span>}
        {children}
      </div>
    </RadioGroupContext.Provider>
  );
}

// packages/vue/src/components/RadioGroup/RadioGroup.vue
<script setup lang="ts">
import { computed, provide, reactive, useId } from "vue";
import "@okkly/design-system/components/RadioGroup/RadioGroup.scss";
import { RadioGroupContextKey } from "./RadioGroupContext";
import type { RadioGroupProps } from "./RadioGroup.types";

const props = withDefaults(defineProps<RadioGroupProps>(), {
  name: undefined,
  defaultValue: undefined,
  disabled: false,
  size: "medium",
  color: "primary",
});

const slots = defineSlots<{
  /** Nested `<Radio value="..." />` elements. */
  default?: () => unknown;
  /** Optional group label, rendered above the options. */
  label?: () => unknown;
}>();

const model = defineModel<string>();
// Seeds the uncontrolled case once on mount, same as React's `defaultValue`.
// A parent that binds `v-model` already has `model.value` set by then, so
// this is a no-op for the controlled case.
if (model.value === undefined && props.defaultValue !== undefined) {
  model.value = props.defaultValue;
}

const generatedName = useId();

function handleSelect(next: string) {
  model.value = next;
}

provide(
  RadioGroupContextKey,
  reactive({
    name: computed(() => props.name ?? generatedName),
    value: computed(() => model.value),
    onSelect: handleSelect,
    disabled: computed(() => props.disabled),
    size: computed(() => props.size),
    color: computed(() => props.color),
  }),
);
</script>

<template>
  <div class="okkly-component okkly-radio-group" role="radiogroup">
    <span v-if="slots.label" class="okkly-radio-group__label"><slot name="label" /></span>
    <slot />
  </div>
</template>
