// packages/react/src/components/DateField/DateField.tsx
"use client";

import { forwardRef, useEffect, useId, useMemo, useRef, useState, type FormEvent } from "react";
import { iconCalendar } from "@okkly/icons";
import {
  maskitoDate,
  maskitoParseDate,
  maskitoStringifyDate,
  type MaskitoDateParams,
} from "@maskito/kit";
import { useMaskito } from "@maskito/react";
import "@okkly/design-system/components/DateField/DateField.scss";
import { Calendar, calendarToneStyle } from "../Calendar/Calendar";
import { Field, getFieldIds } from "../Field/Field";
import { Popover } from "../Popover/Popover";
import type { DateFieldProps } from "./DateField.types";

const DATE_PARAMS: MaskitoDateParams = { mode: "dd/mm/yyyy", separator: "." };

function stringifyDate(value: Date | null | undefined): string {
  if (!value) return "";
  return maskitoStringifyDate(value, DATE_PARAMS);
}

export const DateField = forwardRef<HTMLInputElement, DateFieldProps>(function DateField(
  {
    label,
    hideLabel = false,
    size = "medium",
    color = "primary",
    error = false,
    helperText,
    fullWidth = false,
    disabled = false,
    value: valueProp,
    defaultValue = null,
    onChange,
    min,
    max,
    open: openProp,
    onOpenChange,
    placeholder = "dd.mm.yyyy",
    className,
    id,
    required = false,
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const { helperId } = getFieldIds(inputId, Boolean(label), Boolean(helperText));
  const controlRef = useRef<HTMLDivElement>(null);

  const isControlled = valueProp !== undefined;
  const [uncontrolledValue, setUncontrolledValue] = useState<Date | null>(defaultValue);
  const resolvedValue = isControlled ? (valueProp ?? null) : uncontrolledValue;

  const [text, setText] = useState(() =>
    stringifyDate(valueProp !== undefined ? valueProp : defaultValue),
  );
  const valueKey =
    valueProp === undefined ? "uncontrolled" : valueProp ? valueProp.getTime() : "null";

  useEffect(() => {
    if (valueProp === undefined) return;
    setText(stringifyDate(valueProp));
  }, [valueKey, valueProp]);

  const [uncontrolledOpen, setUncontrolledOpen] = useState(false);
  const isOpen = openProp !== undefined ? openProp : uncontrolledOpen;

  const setOpen = (next: boolean) => {
    if (openProp === undefined) setUncontrolledOpen(next);
    onOpenChange?.(next);
  };

  const dateParams = useMemo<MaskitoDateParams>(() => ({ ...DATE_PARAMS, min, max }), [min, max]);
  const maskOptions = useMemo(() => maskitoDate(dateParams), [dateParams]);
  const maskitoRef = useMaskito({ options: maskOptions });

  const setInputRef = (node: HTMLInputElement | null) => {
    maskitoRef(node);
    if (typeof ref === "function") ref(node);
    else if (ref) ref.current = node;
  };

  const commit = (next: Date | null) => {
    if (!isControlled) setUncontrolledValue(next);
    onChange?.(next);
  };

  const handleInput = (event: FormEvent<HTMLInputElement>) => {
    const next = event.currentTarget.value;
    setText(next);
    if (next === "") {
      commit(null);
      return;
    }
    const parsed = maskitoParseDate(next, dateParams);
    if (parsed) commit(parsed);
  };

  const handleSelect = (date: Date) => {
    setText(maskitoStringifyDate(date, dateParams));
    commit(date);
    setOpen(false);
  };

  // A plain button, not `IconButton`: the field's own control box supplies the
  // padding, so a button with its own 36–52px hit box made the field 14px taller
  // than every other control in a row.
  const trigger = (
    <button
      type="button"
      className="okkly-date-field__trigger"
      disabled={disabled}
      aria-label="Open calendar"
      aria-expanded={isOpen}
      onMouseDown={(event) => event.stopPropagation()}
      onClick={() => setOpen(!isOpen)}
      dangerouslySetInnerHTML={{ __html: iconCalendar }}
    />
  );

  return (
    <>
      <Field
        block="okkly-date-field"
        id={inputId}
        label={label}
        hideLabel={hideLabel}
        size={size}
        color={color}
        error={error}
        helperText={helperText}
        disabled={disabled}
        required={required}
        fullWidth={fullWidth}
        className={className}
        controlProps={{ ref: controlRef }}
        endAdornment={trigger}
      >
        <input
          ref={setInputRef}
          id={inputId}
          type="text"
          inputMode="numeric"
          className="okkly-date-field__input"
          value={text}
          disabled={disabled}
          required={required}
          placeholder={placeholder}
          aria-invalid={error || undefined}
          aria-describedby={helperId}
          onInput={handleInput}
        />
      </Field>

      <Popover
        open={isOpen}
        anchorEl={controlRef.current}
        onClose={() => setOpen(false)}
        placement="bottom-start"
        className="okkly-date-field-popover"
      >
        {/* The popover is portaled, so the field's own colour modifier cannot
            reach the calendar by inheritance — the tone is handed over as an
            inline variable instead. */}
        <Calendar
          value={resolvedValue}
          onSelect={handleSelect}
          min={min}
          max={max}
          style={calendarToneStyle(color)}
        />
      </Popover>
    </>
  );
});

// packages/vue/src/components/DateField/DateField.vue
<script setup lang="ts">
import { computed, ref, useId, useTemplateRef, watch } from "vue";
import { iconCalendar } from "@okkly/icons";
import {
  maskitoDate,
  maskitoParseDate,
  maskitoStringifyDate,
  type MaskitoDateParams,
} from "@maskito/kit";
import { maskito } from "@maskito/vue";
import "@okkly/design-system/components/DateField/DateField.scss";
import Calendar, { calendarToneStyle } from "../Calendar/Calendar.vue";
import type { CalendarValue } from "../Calendar/Calendar.types";
import Field, { getFieldIds } from "../Field/Field.vue";
import Popover from "../Popover/Popover.vue";
import type { DateFieldProps } from "./DateField.types";

// Local `vXxx` bindings are auto-registered as `v-xxx` directives by Vue's
// script-setup compiler — no manual directive registration needed.
const vMaskito = maskito;

const DATE_PARAMS: MaskitoDateParams = { mode: "dd/mm/yyyy", separator: "." };

function stringifyDate(value: Date | null | undefined): string {
  if (!value) return "";
  return maskitoStringifyDate(value, DATE_PARAMS);
}

const props = withDefaults(defineProps<DateFieldProps>(), {
  hideLabel: false,
  size: "medium",
  color: "primary",
  error: false,
  fullWidth: false,
  disabled: false,
  defaultValue: null,
  min: undefined,
  max: undefined,
  placeholder: "dd.mm.yyyy",
  id: undefined,
  required: false,
});

const slots = defineSlots<{
  /** Field label. */
  label?: () => unknown;
  /** Text below field. */
  "helper-text"?: () => unknown;
}>();

// Unlike React's manual `valueProp !== undefined ? valueProp : uncontrolledValue`
// split, `model.value` already resolves controlled vs. uncontrolled —
// `undefined` means genuinely unbound, so it's the only case that falls back
// to `defaultValue`.
const model = defineModel<Date | null>();
const openModel = defineModel<boolean>("open", { default: false });

const resolvedValue = computed<Date | null>(() =>
  model.value !== undefined ? model.value : props.defaultValue,
);

const text = ref(stringifyDate(resolvedValue.value));
// Tracks the value the input itself last committed, so the sync watcher
// below can tell a genuinely external `v-model` change (reformat the text)
// apart from an update it just caused (already reflected in `text` at the
// call site) — same self-inflicted-vs-external distinction WheelColumn's
// scroll watcher makes.
let lastCommitted = model.value;

function commit(next: Date | null) {
  lastCommitted = next;
  model.value = next;
}

watch(
  () => model.value,
  (next) => {
    if (next === lastCommitted) return;
    lastCommitted = next;
    text.value = stringifyDate(next);
  },
);

const generatedId = useId();
const inputId = computed(() => props.id ?? generatedId);
const describedBy = computed(
  () => getFieldIds(inputId.value, false, !!slots["helper-text"]).helperId,
);

const dateParams = computed<MaskitoDateParams>(() => ({
  ...DATE_PARAMS,
  min: props.min,
  max: props.max,
}));
const maskOptions = computed(() => maskitoDate(dateParams.value));

function handleInput(event: Event) {
  const next = (event.target as HTMLInputElement).value;
  text.value = next;
  if (next === "") {
    commit(null);
    return;
  }
  const parsed = maskitoParseDate(next, dateParams.value);
  if (parsed) commit(parsed);
}

function handleSelect(date: Date) {
  text.value = stringifyDate(date);
  commit(date);
  openModel.value = false;
}

// `Calendar` defaults to `mode="single"`, never overridden here, so `value`
// is always `Date | null`.
function handleCalendarChange(value: CalendarValue | null) {
  if (value instanceof Date) handleSelect(value);
}

const fieldRef = useTemplateRef<InstanceType<typeof Field>>("field");
const inputRef = useTemplateRef<HTMLInputElement>("input");
const controlNode = computed(() => fieldRef.value?.controlRef ?? null);

defineExpose({ inputRef });

const toneStyle = computed(() => calendarToneStyle(props.color));
</script>

<template>
  <Field
    ref="field"
    block="okkly-date-field"
    :id="inputId"
    :hide-label="hideLabel"
    :size="size"
    :color="color"
    :error="error"
    :disabled="disabled"
    :required="required"
    :full-width="fullWidth"
  >
    <template v-if="slots.label" #label><slot name="label" /></template>
    <template v-if="slots['helper-text']" #helper-text><slot name="helper-text" /></template>
    <template #end-adornment>
      <!-- A plain button, not `IconButton`: the field's own control box supplies
      the padding, so a button with its own hit box made the field taller than
      every other control in a row. -->
      <button
        type="button"
        class="okkly-date-field__trigger"
        :disabled="disabled"
        aria-label="Open calendar"
        :aria-expanded="openModel"
        @mousedown.stop
        @click="openModel = !openModel"
        v-html="iconCalendar"
      />
    </template>

    <input
      ref="input"
      :id="inputId"
      v-maskito="maskOptions"
      type="text"
      inputmode="numeric"
      class="okkly-date-field__input"
      :value="text"
      :disabled="disabled"
      :required="required"
      :placeholder="placeholder"
      :aria-invalid="error || undefined"
      :aria-describedby="describedBy"
      @input="handleInput"
    />

    <Popover
      :open="openModel"
      :anchor-el="controlNode"
      placement="bottom-start"
      class="okkly-date-field-popover"
      @close="openModel = false"
    >
      <!-- The popover is portaled, so the field's own colour modifier cannot
      reach the calendar by inheritance — the tone is handed over as an inline
      variable instead. -->
      <Calendar
        :model-value="resolvedValue"
        :style="toneStyle"
        :min="min"
        :max="max"
        @update:model-value="handleCalendarChange"
      />
    </Popover>
  </Field>
</template>
