// packages/react/src/components/Skeleton/Skeleton.tsx
"use client";

import { forwardRef, type CSSProperties } from "react";
import "@okkly/design-system/components/Skeleton/Skeleton.scss";
import type { SkeletonProps } from "./Skeleton.types";

function toCssLength(value: number | string | undefined): string | undefined {
  if (value === undefined) return undefined;
  return typeof value === "number" ? `${value / 16}rem` : value;
}

export const Skeleton = forwardRef<HTMLSpanElement, SkeletonProps>(function Skeleton(
  { variant = "text", width, height, animation = "pulse", className, style, ...rest },
  forwardedRef,
) {
  const classes = [
    "okkly-component",
    "okkly-skeleton",
    variant !== "text" && `okkly-skeleton--${variant}`,
    animation === "pulse" && "okkly-skeleton--pulse",
    animation === "wave" && "okkly-skeleton--wave",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const cssVars: CSSProperties = {
    ...(width !== undefined && { "--okkly-skeleton-width": toCssLength(width) }),
    ...(height !== undefined && { "--okkly-skeleton-height": toCssLength(height) }),
    ...style,
  };

  return (
    <span
      ref={forwardedRef}
      aria-hidden="true"
      className={classes}
      style={Object.keys(cssVars).length > 0 ? cssVars : style}
      {...rest}
    />
  );
});

// packages/vue/src/components/Skeleton/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";
import "@okkly/design-system/components/Skeleton/Skeleton.scss";
import type { SkeletonProps } from "./Skeleton.types";

const props = withDefaults(defineProps<SkeletonProps>(), {
  variant: "text",
  animation: "pulse",
});

function toCssLength(value: number | string): string {
  return typeof value === "number" ? `${value / 16}rem` : value;
}

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-skeleton",
    props.variant !== "text" && `okkly-skeleton--${props.variant}`,
    props.animation === "pulse" && "okkly-skeleton--pulse",
    props.animation === "wave" && "okkly-skeleton--wave",
  ]
    .filter(Boolean)
    .join(" "),
);

const cssVars = computed(() => ({
  ...(props.width !== undefined && { "--okkly-skeleton-width": toCssLength(props.width) }),
  ...(props.height !== undefined && { "--okkly-skeleton-height": toCssLength(props.height) }),
}));
</script>

<template>
  <span aria-hidden="true" :class="classes" :style="cssVars" />
</template>
