// packages/vue/src/components/Fab/Fab.vue
<script setup lang="ts">
import { computed, useTemplateRef } from "vue";
import "@okkly/design-system/components/FAB/FAB.scss";
import { useRipple } from "@okkly/vue-composables";
import Ripple from "../Ripple/Ripple.vue";
import type { FabProps } from "./Fab.types";

const props = withDefaults(defineProps<FabProps>(), {
  variant: "standard",
  color: "primary",
  size: "medium",
  disableRipple: false,
  disabled: false,
  href: undefined,
});

// The returned object is the runtime slots record — using it directly avoids
// the circular inference `useSlots()` hits when the same file declares them.
const slots = defineSlots<{
  /** Glyph slot — always present. */
  default?: () => unknown;
  /** Label slot. Filling it grows the FAB into an extended pill (icon + text) instead of a plain circle. */
  label?: () => unknown;
}>();

const root = useTemplateRef<HTMLElement>("root");
const { ripples, events, hideRipple } = useRipple(root);

const showRipple = computed(() => !props.disableRipple && !props.disabled);
const hasLabel = computed(() => !!slots.label);

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-fab",
    props.variant !== "standard" && `okkly-fab--${props.variant}`,
    props.color !== "primary" && `okkly-fab--color-${props.color}`,
    hasLabel.value && "okkly-fab--extended",
    props.size !== "medium" && `okkly-fab--${props.size}`,
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <component
    :is="href ? 'a' : 'button'"
    ref="root"
    :class="classes"
    :type="href ? undefined : 'button'"
    :href="href && !disabled ? href : undefined"
    :disabled="href ? undefined : disabled"
    :aria-disabled="href && disabled ? true : undefined"
    v-on="showRipple ? events : {}"
  >
    <Ripple v-if="showRipple" :ripples="ripples" :on-ripple-end="hideRipple" />
    <span class="okkly-fab__icon" aria-hidden="true"><slot /></span>
    <span v-if="hasLabel" class="okkly-fab__label okkly-truncation-ellipsis"
      ><slot name="label"
    /></span>
  </component>
</template>

// packages/react/src/components/FAB/FAB.tsx
"use client";

import { forwardRef, useRef, type AnchorHTMLAttributes, type ButtonHTMLAttributes } from "react";
import "@okkly/design-system/components/FAB/FAB.scss";
import { useRipple } from "@okkly/react-hooks";
import { Ripple } from "../Ripple/Ripple";
import type { FabProps } from "./FAB.types";

export const Fab = forwardRef<HTMLButtonElement | HTMLAnchorElement, FabProps>(function Fab(
  {
    variant = "standard",
    color = "primary",
    size = "medium",
    icon,
    label,
    disableRipple = false,
    disabled = false,
    className,
    href,
    ...rest
  },
  forwardedRef,
) {
  const localRef = useRef<HTMLButtonElement | HTMLAnchorElement>(null);
  const setRef = (node: HTMLButtonElement | HTMLAnchorElement | null) => {
    localRef.current = node;
    if (typeof forwardedRef === "function") forwardedRef(node);
    else if (forwardedRef) forwardedRef.current = node;
  };

  const showRipple = !disableRipple && !disabled;
  const { ripples, events, hideRipple } = useRipple(localRef);

  const classes = [
    "okkly-component",
    "okkly-fab",
    variant !== "standard" && `okkly-fab--${variant}`,
    color !== "primary" && `okkly-fab--color-${color}`,
    label != null && "okkly-fab--extended",
    size !== "medium" && `okkly-fab--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const content = (
    <>
      {showRipple && <Ripple ripples={ripples} onRippleEnd={hideRipple} />}
      <span className="okkly-fab__icon" aria-hidden="true">
        {icon}
      </span>
      {label != null && <span className="okkly-fab__label okkly-truncation-ellipsis">{label}</span>}
    </>
  );

  if (href) {
    return (
      <a
        ref={setRef as (node: HTMLAnchorElement | null) => void}
        href={disabled ? undefined : href}
        aria-disabled={disabled || undefined}
        className={classes}
        {...(showRipple ? events : {})}
        {...(rest as AnchorHTMLAttributes<HTMLAnchorElement>)}
      >
        {content}
      </a>
    );
  }

  return (
    <button
      ref={setRef as (node: HTMLButtonElement | null) => void}
      type="button"
      disabled={disabled}
      className={classes}
      {...(showRipple ? events : {})}
      {...(rest as ButtonHTMLAttributes<HTMLButtonElement>)}
    >
      {content}
    </button>
  );
});
