// packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx
"use client";

import { useId, useState } from "react";
import "@okkly/design-system/components/CheckboxGroup/CheckboxGroup.scss";

import { CheckboxGroupContext } from "./CheckboxGroupContext";
import type { CheckboxGroupProps } from "./CheckboxGroup.types";

/**
 * Groups `Checkbox` children via context — nest them directly rather than
 * passing an options array, mirroring RadioGroup's composition pattern
 * (multi-select instead of single). Deliberate gaps vs a hypothetical MUI
 * FormGroup: owns `value`/`onChange` as `string[]`, propagates size/color.
 */
export function CheckboxGroup({
  name,
  value,
  defaultValue,
  onChange,
  disabled = false,
  size = "medium",
  color = "primary",
  label,
  children,
  className,
}: CheckboxGroupProps) {
  const generatedName = useId();
  const [internalValue, setInternalValue] = useState<string[]>(defaultValue ?? []);
  const currentValue = value ?? internalValue;

  const handleToggle = (option: string, checked: boolean) => {
    const next = checked
      ? currentValue.includes(option)
        ? currentValue
        : [...currentValue, option]
      : currentValue.filter((item) => item !== option);

    if (value === undefined) setInternalValue(next);
    onChange?.(next);
  };

  const classes = ["okkly-component", "okkly-checkbox-group", className].filter(Boolean).join(" ");

  return (
    <CheckboxGroupContext.Provider
      value={{
        name: name ?? generatedName,
        value: currentValue,
        onToggle: handleToggle,
        disabled,
        size,
        color,
      }}
    >
      <div
        role="group"
        aria-label={typeof label === "string" ? label : undefined}
        className={classes}
      >
        {label && <span className="okkly-checkbox-group__label">{label}</span>}
        {children}
      </div>
    </CheckboxGroupContext.Provider>
  );
}

// packages/vue/src/components/CheckboxGroup/CheckboxGroup.vue
<script setup lang="ts">
import { computed, provide, reactive, useId } from "vue";
import "@okkly/design-system/components/CheckboxGroup/CheckboxGroup.scss";
import { CheckboxGroupContextKey } from "./CheckboxGroupContext";
import type { CheckboxGroupProps } from "./CheckboxGroup.types";

const props = withDefaults(defineProps<CheckboxGroupProps>(), {
  name: undefined,
  defaultValue: undefined,
  disabled: false,
  size: "medium",
  color: "primary",
});

const slots = defineSlots<{
  /** Nested `<Checkbox value="..." />` elements. */
  default?: () => unknown;
  /** Optional group label, rendered above the options. */
  label?: () => unknown;
}>();

const model = defineModel<string[]>();
// `defaultValue` is only ever read here, never written into `model` — an
// eager write would emit `update:modelValue` on mount (assigning to `model`
// always emits, controlled or not), which React's lazy `useState` initializer
// never does since nothing calls `onChange` before the user acts. See
// Slider.vue for the same fix applied there.
const currentValue = computed(() => model.value ?? props.defaultValue ?? []);

const generatedName = useId();

function handleToggle(option: string, checked: boolean) {
  const current = currentValue.value;
  const next = checked
    ? current.includes(option)
      ? current
      : [...current, option]
    : current.filter((item) => item !== option);
  model.value = next;
}

provide(
  CheckboxGroupContextKey,
  reactive({
    name: computed(() => props.name ?? generatedName),
    value: currentValue,
    onToggle: handleToggle,
    disabled: computed(() => props.disabled),
    size: computed(() => props.size),
    color: computed(() => props.color),
  }),
);
</script>

<template>
  <div class="okkly-component okkly-checkbox-group" role="group">
    <span v-if="slots.label" class="okkly-checkbox-group__label"><slot name="label" /></span>
    <slot />
  </div>
</template>
