// packages/react/src/components/Avatar/Avatar.tsx
"use client";

import { forwardRef, useState } from "react";
import "@okkly/design-system/components/Avatar/Avatar.scss";
import type { AvatarProps } from "./Avatar.types";

export const Avatar = forwardRef<HTMLDivElement, AvatarProps>(function Avatar(
  { src, alt, initials, status, shape = "circle", size = "md", color = "mint", className, ...rest },
  ref,
) {
  const [imageFailed, setImageFailed] = useState(false);
  const showImage = !!src && !imageFailed;

  const classes = [
    "okkly-component",
    "okkly-avatar",
    shape === "rounded" && "okkly-avatar--rounded",
    size !== "md" && `okkly-avatar--${size}`,
    !showImage && color !== "mint" && `okkly-avatar--color-${color}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div ref={ref} className={classes} role={alt ? "img" : undefined} aria-label={alt} {...rest}>
      {showImage ? (
        <img
          className="okkly-avatar__image"
          src={src}
          alt=""
          onError={() => setImageFailed(true)}
        />
      ) : (
        <span className="okkly-avatar__initials" aria-hidden="true">
          {(initials ?? "").slice(0, 2)}
        </span>
      )}
      {status && (
        <span
          className={[
            "okkly-avatar__status",
            status === "offline" && "okkly-avatar__status--offline",
          ]
            .filter(Boolean)
            .join(" ")}
          aria-hidden="true"
        />
      )}
    </div>
  );
});

// packages/vue/src/components/Avatar/Avatar.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import "@okkly/design-system/components/Avatar/Avatar.scss";
import type { AvatarProps } from "./Avatar.types";

const props = withDefaults(defineProps<AvatarProps>(), {
  src: undefined,
  alt: undefined,
  initials: undefined,
  status: undefined,
  shape: "circle",
  size: "md",
  color: "mint",
});

const imageFailed = ref(false);
const showImage = computed(() => !!props.src && !imageFailed.value);

const classes = computed(() =>
  [
    "okkly-component",
    "okkly-avatar",
    props.shape === "rounded" && "okkly-avatar--rounded",
    props.size !== "md" && `okkly-avatar--${props.size}`,
    !showImage.value && props.color !== "mint" && `okkly-avatar--color-${props.color}`,
  ]
    .filter(Boolean)
    .join(" "),
);

const statusClasses = computed(() =>
  ["okkly-avatar__status", props.status === "offline" && "okkly-avatar__status--offline"]
    .filter(Boolean)
    .join(" "),
);

function handleImageError() {
  imageFailed.value = true;
}
</script>

<template>
  <div :class="classes" :role="alt ? 'img' : undefined" :aria-label="alt">
    <img v-if="showImage" class="okkly-avatar__image" :src="src" alt="" @error="handleImageError" />
    <span v-else class="okkly-avatar__initials" aria-hidden="true">{{
      (initials ?? "").slice(0, 2)
    }}</span>
    <span v-if="status" :class="statusClasses" aria-hidden="true" />
  </div>
</template>
