// packages/react/src/components/ChipGroup/ChipGroup.tsx
"use client";

import { type KeyboardEvent, type MouseEvent } from "react";
import "@okkly/design-system/components/ChipGroup/ChipGroup.scss";
import { Chip } from "../Chip/Chip";
import type { ChipGroupItem, ChipGroupProps } from "./ChipGroup.types";

function itemKey(item: ChipGroupItem, index: number) {
  return item.value ?? String(index);
}

function isItemSelected(
  itemValue: string,
  value: string | string[] | undefined,
  item: ChipGroupItem,
  exclusive: boolean,
) {
  if (value !== undefined) {
    return exclusive ? value === itemValue : Array.isArray(value) && value.includes(itemValue);
  }
  return item.selected ?? false;
}

export function ChipGroup({
  children,
  items,
  value,
  onChange,
  exclusive = false,
  color = "primary",
  disabled = false,
  className,
}: ChipGroupProps) {
  const classes = [
    "okkly-component",
    "okkly-chip-group",
    color !== "primary" && `okkly-chip-group--color-${color}`,
    disabled && "okkly-chip-group--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const handleToggle = (
    event: MouseEvent<HTMLDivElement> | KeyboardEvent<HTMLDivElement>,
    item: ChipGroupItem,
    itemValue: string,
  ) => {
    if (disabled || item.disabled) return;

    if (onChange) {
      if (exclusive) {
        onChange(itemValue);
      } else {
        const current = Array.isArray(value) ? value : [];
        const next = current.includes(itemValue)
          ? current.filter((entry) => entry !== itemValue)
          : [...current, itemValue];
        onChange(next);
      }
    }

    item.onClick?.(event, item);
  };

  return (
    <div className={classes} role={items && (onChange || exclusive) ? "group" : undefined}>
      {items
        ? items.map((item, index) => {
            const itemValue = itemKey(item, index);
            const selected = isItemSelected(itemValue, value, item, exclusive);
            const interactive = !!onChange || !!item.onClick;
            const chipDisabled = disabled || item.disabled;

            return (
              <Chip
                key={itemValue}
                label={item.label}
                selected={selected}
                disabled={chipDisabled}
                removable={!!item.onRemove}
                onRemove={item.onRemove ? (event) => item.onRemove?.(event, item) : undefined}
                onClick={interactive ? (event) => handleToggle(event, item, itemValue) : undefined}
              />
            );
          })
        : children}
    </div>
  );
}

// packages/vue/src/components/ChipGroup/ChipGroup.vue
<script setup lang="ts">
import { computed, normalizeClass, useAttrs } from "vue";
import "@okkly/design-system/components/ChipGroup/ChipGroup.scss";
import Chip from "../Chip/Chip.vue";
import type { ChipGroupItem, ChipGroupProps } from "./ChipGroup.types";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ChipGroupProps>(), {
  items: undefined,
  exclusive: false,
  color: "primary",
  disabled: false,
});

const slots = defineSlots<{
  /** Custom chip nodes — no built-in selection wiring. */
  default?: () => unknown;
}>();

const model = defineModel<string | string[]>();

const attrs = useAttrs();
const restAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
const classes = computed(() =>
  normalizeClass([
    "okkly-component",
    "okkly-chip-group",
    props.color !== "primary" && `okkly-chip-group--color-${props.color}`,
    props.disabled && "okkly-chip-group--disabled",
    attrs.class,
  ]),
);

// See the "Deliberate simplification" note in ChipGroup.types.ts.
const isSelectable = computed(() => props.exclusive || model.value !== undefined);
const hasGroupRole = computed(
  () => !!props.items && (isSelectable.value || props.items.some((item) => item.onClick)),
);

function itemKey(item: ChipGroupItem, index: number) {
  return item.value ?? String(index);
}

function isItemSelected(itemValue: string, item: ChipGroupItem) {
  if (model.value !== undefined) {
    return props.exclusive
      ? model.value === itemValue
      : Array.isArray(model.value) && model.value.includes(itemValue);
  }
  return item.selected ?? false;
}

function handleToggle(event: MouseEvent | KeyboardEvent, item: ChipGroupItem, itemValue: string) {
  if (props.disabled || item.disabled) return;

  if (props.exclusive) {
    model.value = itemValue;
  } else {
    const current = Array.isArray(model.value) ? model.value : [];
    model.value = current.includes(itemValue)
      ? current.filter((entry) => entry !== itemValue)
      : [...current, itemValue];
  }

  item.onClick?.(event, item);
}

// `:onClick` (`v-bind`), not `@click` (`v-on`): a call-expression bound with
// `v-on` compiles to an inline statement that *invokes* this function and
// discards whatever it returns, rather than using the return value as the
// listener — `v-bind`ing the `onClick` vnode prop directly is what actually
// leaves the listener attached, or omits it, per chip.
function clickHandlerFor(item: ChipGroupItem, itemValue: string) {
  if (!isSelectable.value && !item.onClick) return undefined;
  return (event: MouseEvent | KeyboardEvent) => handleToggle(event, item, itemValue);
}
</script>

<template>
  <div :class="classes" v-bind="restAttrs" :role="hasGroupRole ? 'group' : undefined">
    <template v-if="items">
      <Chip
        v-for="(item, index) in items"
        :key="itemKey(item, index)"
        :selected="isItemSelected(itemKey(item, index), item)"
        :disabled="disabled || item.disabled"
        :removable="!!item.onRemove"
        :onClick="clickHandlerFor(item, itemKey(item, index))"
        @remove="item.onRemove?.($event, item)"
        >{{ item.label }}</Chip
      >
    </template>
    <slot v-else />
  </div>
</template>
