// packages/react/src/components/Select/Select.tsx
"use client";

import {
  forwardRef,
  Fragment,
  useCallback,
  useId,
  useRef,
  useState,
  type ForwardedRef,
  type ReactElement,
} from "react";
import { iconCheck, iconChevronDown, iconX } from "@okkly/icons";
import { useSelect, type SelectOption } from "@okkly/react-hooks";
import "@okkly/design-system/components/Select/Select.scss";
import { Popper } from "../Popper/Popper";
import { Checkbox } from "../Checkbox/Checkbox";
import { Chip } from "../Chip/Chip";
import { Spinner } from "../Spinner/Spinner";
import { Field, getFieldIds } from "../Field/Field";
import { useOutsideDismiss } from "../Field/useOutsideDismiss";
import { OptionScope } from "../Option/Option";
import type { SelectRenderInputParams, SelectProps } from "./Select.types";

function SelectInner<T = string>(
  {
    options,
    value,
    defaultValue,
    multiple = false,
    onChange,
    disabled = false,
    required = false,
    open,
    onOpenChange,
    label,
    hideLabel = false,
    placeholder = "Select…",
    size = "medium",
    color = "primary",
    error = false,
    helperText,
    fullWidth = false,
    loading = false,
    name,
    groupBy,
    isOptionEqualToValue,
    limitTags = 2,
    disableCloseOnSelect,
    disableClearable = false,
    renderValue,
    renderOption,
    renderInput,
    renderGroup,
    renderNoOptions,
    renderLoading,
    noOptionsText = "No options",
    loadingText = "Loading…",
    clearText = "Clear",
    popupWidth,
    className,
    id,
  }: SelectProps<T>,
  forwardedRef: ForwardedRef<HTMLDivElement>,
) {
  const generatedId = useId();
  const fieldId = id ?? generatedId;
  const { labelId, helperId } = getFieldIds(fieldId, Boolean(label), Boolean(helperText));
  const triggerRef = useRef<HTMLDivElement | null>(null);
  const controlRef = useRef<HTMLDivElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  /**
   * The anchor has to be state, not just the ref: `anchorEl` is read during
   * render, and attaching a ref does not schedule one. With a plain ref, a
   * popup that is already open on the first render — a controlled `open` — sees
   * `null` and never gets positioned at all, so it lands at the viewport
   * origin. The ref is kept alongside for the click/dismiss containment checks,
   * which run in handlers where a re-render would be wasted.
   */
  const [controlNode, setControlNode] = useState<HTMLDivElement | null>(null);
  const setControlRef = useCallback((node: HTMLDivElement | null) => {
    controlRef.current = node;
    setControlNode(node);
  }, []);

  const select = useSelect({
    options,
    value,
    defaultValue,
    multiple,
    onChange,
    disabled,
    open,
    onOpenChange,
    isOptionEqualToValue,
    groupBy,
    disableCloseOnSelect,
    disableClearable,
  });

  // Popper, unlike Popover, has no backdrop and no dismissal of its own. The
  // whole control counts as "inside" — clicking its padding opens the popup, so
  // it must not close it on the way down.
  useOutsideDismiss([controlRef, panelRef], select.isOpen, () => select.setOpen(false));

  /**
   * The chevron and the field's own padding live outside the trigger div (they
   * are Field adornments), so without this they would be dead space. Clicks
   * that started on the trigger, a chip's × or the clear button are left to
   * their own handlers — otherwise every one of them would toggle twice.
   */
  function handleControlClick(event: React.MouseEvent<HTMLDivElement>) {
    if (disabled) return;
    // The popup is portaled out of the control but still React's child, and
    // React propagates synthetic events along its own tree — so without this a
    // click on an option would arrive here and toggle the popup shut again.
    if (!controlRef.current?.contains(event.target as Node)) return;
    if ((event.target as HTMLElement).closest("button, [role='combobox']")) return;
    select.setOpen(!select.isOpen);
    triggerRef.current?.focus();
  }

  const { selectedOptions } = select;
  const hasValue = selectedOptions.length > 0;

  const triggerProps = select.getTriggerProps({
    id: fieldId,
    className: "okkly-select__trigger okkly-select__input",
    "aria-invalid": error || undefined,
    "aria-required": required || undefined,
    "aria-labelledby": labelId,
    "aria-describedby": helperId,
    ref: (node) => {
      triggerRef.current = node as HTMLDivElement | null;
      if (typeof forwardedRef === "function") forwardedRef(node as HTMLDivElement | null);
      else if (forwardedRef) forwardedRef.current = node as HTMLDivElement | null;
    },
  });

  const clearProps = select.getClearProps({
    className: "okkly-select__clear",
    "aria-label": clearText,
  });

  function renderTriggerContent() {
    if (renderValue) return renderValue(selectedOptions);

    if (!hasValue) {
      return (
        <span className="okkly-select__value okkly-select__value--placeholder">{placeholder}</span>
      );
    }

    if (!multiple) {
      return <span className="okkly-select__value">{selectedOptions[0]?.label}</span>;
    }

    const shown = limitTags < 0 ? selectedOptions : selectedOptions.slice(0, limitTags);
    const overflow = selectedOptions.length - shown.length;

    return (
      <span className="okkly-select__chips">
        {shown.map((option) => (
          <Chip
            key={String(option.value)}
            label={option.label}
            size="small"
            variant="solid"
            removable={!disabled}
            // The trigger is a div rather than a button precisely so these
            // remove buttons are legal here; stopping propagation keeps the
            // click from also toggling the popup.
            onRemove={(event) => {
              event?.stopPropagation?.();
              select.removeValue(event ?? null, option);
            }}
          />
        ))}
        {overflow > 0 && <span className="okkly-select__overflow">+{overflow}</span>}
      </span>
    );
  }

  function renderRow(option: SelectOption<T>, index: number) {
    const selected = select.isSelected(option);
    const highlighted = select.highlightedIndex === index;
    const optionProps = select.getOptionProps(index, {
      className: [
        "okkly-select__option",
        highlighted && "okkly-select__option--highlighted",
        selected && "okkly-select__option--selected",
        option.disabled && "okkly-select__option--disabled",
      ]
        .filter(Boolean)
        .join(" "),
    });
    const key = `${String(option.value)}-${index}`;

    if (renderOption) {
      // The row is keyed here rather than through `props`: React 19 warns when
      // a spread object carries `key`, and `<li {...props}>` is the whole point
      // of the prop. Callers get a props object they can spread as-is.
      return (
        <Fragment key={key}>
          {renderOption(optionProps as React.HTMLAttributes<HTMLLIElement>, option, {
            selected,
            highlighted,
            index,
            disabled: option.disabled === true,
            multiple,
            size,
          })}
        </Fragment>
      );
    }

    return (
      <li key={key} {...optionProps}>
        {multiple && (
          <Checkbox
            checked={selected}
            disabled={option.disabled}
            size="small"
            readOnly
            tabIndex={-1}
          />
        )}
        <span className="okkly-select__option-label">{option.label}</span>
        {!multiple && selected && (
          <span
            className="okkly-select__option-check"
            dangerouslySetInnerHTML={{ __html: iconCheck }}
            aria-hidden="true"
          />
        )}
      </li>
    );
  }

  function renderListContent() {
    if (loading) {
      if (renderLoading) return renderLoading();
      return (
        <li className="okkly-select__loading">
          <Spinner size="small" />
          {loadingText}
        </li>
      );
    }
    if (select.flatOptions.length === 0) {
      if (renderNoOptions) return renderNoOptions();
      return <li className="okkly-select__empty">{noOptionsText}</li>;
    }
    if (select.groupedOptions) {
      return select.groupedOptions.map((group) => {
        const children = group.options.map(({ option, index }) => renderRow(option, index));
        if (renderGroup)
          return renderGroup({ key: group.key, label: group.label, group, children });
        return (
          <li key={group.key} role="presentation">
            <span className="okkly-select__group-label" role="presentation">
              {group.label}
            </span>
            <ul className="okkly-select__group-options" role="group" aria-label={group.label}>
              {children}
            </ul>
          </li>
        );
      });
    }
    return select.flatOptions.map((option, index) => renderRow(option, index));
  }

  const endAdornment = (
    <>
      {!disableClearable && hasValue && !disabled && (
        <button {...clearProps}>
          <span dangerouslySetInnerHTML={{ __html: iconX }} aria-hidden="true" />
        </button>
      )}
      <span
        className="okkly-select__chevron"
        dangerouslySetInnerHTML={{ __html: iconChevronDown }}
        aria-hidden="true"
      />
    </>
  );

  return (
    <Field
      block="okkly-select"
      id={fieldId}
      label={label}
      hideLabel={hideLabel}
      required={required}
      size={size}
      color={color}
      error={error}
      helperText={helperText}
      disabled={disabled}
      fullWidth={fullWidth}
      endAdornment={renderInput ? undefined : endAdornment}
      // A `<label for>` can only target a real form control, and the trigger is
      // a div[role="combobox"]; the trigger points back with aria-labelledby.
      htmlFor={false}
      controlProps={{ ref: setControlRef, onClick: handleControlClick }}
      className={className}
    >
      {/* A custom trigger decides where the clear button and chevron go, so
          they are handed to `renderInput` instead of being placed by the
          Field — leaving them in both places would draw two chevrons. */}
      {renderInput ? (
        renderInput({
          triggerProps: triggerProps as SelectRenderInputParams<T>["triggerProps"],
          value: renderTriggerContent(),
          selected: selectedOptions,
          endAdornment,
          state: { open: select.isOpen, disabled, error, multiple, size, color },
        })
      ) : (
        <div {...triggerProps}>{renderTriggerContent()}</div>
      )}

      {name &&
        (multiple ? selectedOptions : selectedOptions.slice(0, 1)).map((option) => (
          <input
            key={String(option.value)}
            type="hidden"
            name={name}
            value={String(option.value)}
          />
        ))}

      <Popper
        open={select.isOpen}
        // The bordered control box, not the trigger div inside it: the trigger
        // sits within the control's padding, so anchoring there made the panel
        // narrower than the field and started it 12px too high — swallowing the
        // gap and confusing `flip` about how much room is left below.
        anchorEl={controlNode}
        placement="bottom-start"
        className="okkly-select-popper"
        modifiers={[{ name: "offset", options: { offset: [0, 4] } }]}
        matchAnchorWidth="min"
        style={popupWidth === undefined ? undefined : { width: popupWidth }}
        role="presentation"
      >
        {/* The panel is portaled to <body>, so the field's size modifier does
            not reach it by inheritance — it is copied on explicitly. */}
        <div
          ref={panelRef}
          className={
            size === "medium"
              ? "okkly-select-popover"
              : `okkly-select-popover okkly-select-popover--${size}`
          }
        >
          {/* Names the BEM block for the option primitives, so a `renderOption`
              built from them picks up this listbox's styling. */}
          <OptionScope block="okkly-select">
            <ul {...select.getListboxProps({ className: "okkly-select__listbox" })}>
              {renderListContent()}
            </ul>
          </OptionScope>
        </div>
      </Popper>
    </Field>
  );
}

export const Select = forwardRef(SelectInner) as <T = string>(
  props: SelectProps<T> & { ref?: ForwardedRef<HTMLDivElement> },
) => ReactElement;

// packages/angular/src/components/Select/Select.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  ElementRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  effect,
  inject,
  input,
  model,
  output,
  signal,
  viewChild,
} from "@angular/core";
import { iconChevronDown, iconX } from "@okkly/icons";
import { OkklyCheckbox } from "../Checkbox/Checkbox";
import { OkklyChip } from "../Chip/Chip";
import {
  OkklyField,
  OkklyFieldEndAdornment,
  getFieldIds,
  type FieldColor,
  type FieldSize,
} from "../Field/Field";
import { OkklyIcon } from "../Icon/Icon";
import {
  OkklyOptionCheck,
  OkklyOptionLabel,
  OkklyOptionRow,
  OkklyOptionScope,
} from "../Option/Option";
import { OkklyPopper } from "../Popper/Popper";
import { OkklySpinner } from "../Spinner/Spinner";
import {
  findNextEnabledIndex,
  groupOptions,
  normalizeMultipleValue,
  normalizeSingleValue,
  type OptionGroup,
  type SelectOption,
  type SelectionChangeEvent,
} from "./selection";

export type SelectSize = FieldSize;
export type SelectColor = FieldColor;
export type { SelectOption, SelectionChangeEvent, SelectionChangeReason } from "./selection";

let nextId = 0;

const POPPER_MODIFIERS = [{ name: "offset", options: { offset: [0, 4] } }];

/**
 * Props follow MUI's Select API (https://mui.com/material-ui/api/select/) as
 * closely as this design allows: `options`/`multiple`/`disabled`/`label`/
 * `error`/`helperText`/`fullWidth`/`size`/`required`/`name`/`groupBy`/
 * `limitTags`/`disableCloseOnSelect`/`disableClearable`/`noOptionsText`/
 * `loadingText` all match name-for-name, and `open`/`value` become
 * two-way-bindable `model()`s (`[(open)]`, `[(value)]`).
 *
 * Deliberate gaps: no generic option type — `SelectOption` is fixed to
 * `{ value: string; label: string; disabled?: boolean }`, since Angular
 * components in this package do not take a type parameter (see
 * `OkklySegmentedToggle`'s `items`). No `renderValue`/`renderOption`/
 * `renderInput`/`renderGroup`/`renderNoOptions`/`renderLoading` and no
 * `isOptionEqualToValue` — Angular has no `ReactNode`/render-prop
 * equivalent, so a row is always the built-in label (+ checkbox in
 * `multiple` mode, + tick when selected) built from the `OkklyOption*`
 * primitives, and values compare with `===`. No `className`/`class`
 * forwarding onto the field's own root, matching `OkklyTextField`. A
 * controlled `value`/`onChange` pair becomes `[(value)]`, with the reason
 * for a change (`selectOption`/`removeOption`/`clear`) reported separately
 * through `(change)`.
 */
@Component({
  selector: "okkly-select",
  changeDetection: ChangeDetectionStrategy.OnPush,
  // Every rule this renders lives in @okkly/design-system as a global BEM
  // class inside the `okkly` cascade layer; scoping attributes would only add
  // noise to the DOM.
  encapsulation: ViewEncapsulation.None,
  imports: [
    NgTemplateOutlet,
    OkklyField,
    OkklyFieldEndAdornment,
    OkklyPopper,
    OkklyCheckbox,
    OkklyChip,
    OkklySpinner,
    OkklyIcon,
    OkklyOptionScope,
    OkklyOptionRow,
    OkklyOptionLabel,
    OkklyOptionCheck,
  ],
  templateUrl: "./Select.html",
})
export class OkklySelect {
  /**
   * Options.
   *
   * @default []
   */
  readonly options = input<readonly SelectOption[]>([]);
  /**
   * Value. Two-way bindable as `[(value)]` — a string, or a string array in
   * `multiple` mode.
   *
   * @default null
   */
  readonly value = model<string | string[] | null>(null);
  /**
   * Multiple.
   *
   * @default false
   */
  readonly multiple = input(false, { transform: booleanAttribute });
  /**
   * Disabled.
   *
   * @default false
   */
  readonly disabled = input(false, { transform: booleanAttribute });
  /**
   * Marks the field required and shows a dante asterisk after the label.
   *
   * @default false
   */
  readonly required = input(false, { transform: booleanAttribute });
  /**
   * Whether the listbox is open. Two-way bindable as `[(open)]`.
   *
   * @default false
   */
  readonly open = model(false);
  /**
   * Label.
   *
   * @default undefined
   */
  readonly label = input<string>();
  /**
   * Visually hides the label (still present for assistive tech).
   *
   * @default false
   */
  readonly hideLabel = input(false, { transform: booleanAttribute });
  /**
   * Placeholder.
   *
   * @default "Select…"
   */
  readonly placeholder = input("Select…");
  /**
   * Size.
   *
   * @default "medium"
   */
  readonly size = input<SelectSize>("medium");
  /**
   * Color.
   *
   * @default "primary"
   */
  readonly color = input<SelectColor>("primary");
  /**
   * Error.
   *
   * @default false
   */
  readonly error = input(false, { transform: booleanAttribute });
  /**
   * Helper text.
   *
   * @default undefined
   */
  readonly helperText = input<string>();
  /**
   * Full width.
   *
   * @default false
   */
  readonly fullWidth = input(false, { transform: booleanAttribute });
  /**
   * Loading.
   *
   * @default false
   */
  readonly loading = input(false, { transform: booleanAttribute });
  /**
   * Emits hidden inputs so the value reaches a plain `<form>` submit.
   *
   * @default undefined
   */
  readonly name = input<string>();
  /**
   * Groups options under sticky headers; also reorders them so groups are contiguous.
   *
   * @default undefined
   */
  readonly groupBy = input<(option: SelectOption) => string>();
  /**
   * Chips shown before collapsing to "+N". `-1` shows all. Multi-select only.
   *
   * @default 2
   */
  readonly limitTags = input(2);
  /**
   * Keeps the popup open after picking. Defaults to `true` for `multiple`.
   *
   * @default undefined
   */
  readonly disableCloseOnSelect = input<boolean>();
  /**
   * Disable clearable.
   *
   * @default false
   */
  readonly disableClearable = input(false, { transform: booleanAttribute });
  /**
   * No options text.
   *
   * @default "No options"
   */
  readonly noOptionsText = input("No options");
  /**
   * Loading text.
   *
   * @default "Loading…"
   */
  readonly loadingText = input("Loading…");
  /**
   * Clear text.
   *
   * @default "Clear"
   */
  readonly clearText = input("Clear");
  /**
   * Width of the dropdown panel. It is never narrower than the field; this is
   * for the case where the options need more room than the trigger has.
   *
   * @default undefined
   */
  readonly popupWidth = input<number | string>();
  /**
   * Id of the field. Generated when omitted.
   *
   * @default undefined
   */
  readonly id = input<string>();

  /** Emits the reason behind a `value` change — `[(value)]` already carries the new value. */
  readonly change = output<SelectionChangeEvent>();

  protected readonly iconChevronDown = iconChevronDown;
  protected readonly iconX = iconX;
  protected readonly popperModifiers = POPPER_MODIFIERS;

  private readonly generatedId = `okkly-select-${nextId++}`;
  protected readonly fieldId = computed(() => this.id() ?? this.generatedId);
  protected readonly labelId = computed(
    () => getFieldIds(this.fieldId(), !!this.label(), !!this.helperText()).labelId,
  );
  protected readonly helperId = computed(
    () => getFieldIds(this.fieldId(), !!this.label(), !!this.helperText()).helperId,
  );
  protected readonly listboxId = computed(() => `${this.fieldId()}-listbox`);

  private readonly document = inject(DOCUMENT);
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly fieldRef = viewChild<OkklyField>("field");
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  private readonly triggerElement = viewChild<ElementRef<HTMLElement>>("trigger");
  /** The field's control box, anchoring the popup — the counterpart of React's `controlRef`. */
  protected readonly controlElement = computed(() => this.fieldRef()?.controlElement() ?? null);

  protected readonly highlightedIndex = signal(-1);
  private readonly typeahead = { query: "", at: 0 };

  private readonly keepOpenOnSelect = computed(
    () => this.disableCloseOnSelect() ?? this.multiple(),
  );

  private readonly grouped = computed(() => {
    const groupBy = this.groupBy();
    return groupBy ? groupOptions(this.options(), groupBy) : null;
  });

  /** Options in render order — reordered when `groupBy` is set. */
  protected readonly flatOptions = computed<readonly SelectOption[]>(
    () => this.grouped()?.flat ?? this.options(),
  );
  /** `null` unless `groupBy` is set. */
  protected readonly groupedOptions = computed<OptionGroup[] | null>(
    () => this.grouped()?.groups ?? null,
  );

  protected isSelected(option: SelectOption): boolean {
    if (this.multiple()) {
      return normalizeMultipleValue(this.value()).includes(option.value);
    }
    return normalizeSingleValue(this.value()) === option.value;
  }

  protected readonly selectedOptions = computed(() =>
    this.flatOptions().filter((option) => this.isSelected(option)),
  );
  protected readonly hasValue = computed(() => this.selectedOptions().length > 0);

  protected readonly shownChips = computed(() => {
    const limit = this.limitTags();
    const selected = this.selectedOptions();
    return limit < 0 ? selected : selected.slice(0, limit);
  });
  protected readonly chipOverflow = computed(
    () => this.selectedOptions().length - this.shownChips().length,
  );

  /** Options rendered as hidden `<input>`s so `name` reaches a plain form submit. */
  protected readonly hiddenInputs = computed(() => {
    const selected = this.selectedOptions();
    return this.multiple() ? selected : selected.slice(0, 1);
  });

  protected readonly triggerActivedescendant = computed(() => {
    const index = this.highlightedIndex();
    return this.open() && index >= 0 ? `${this.listboxId()}-option-${index}` : null;
  });

  protected readonly popupStyle = computed<Record<string, string>>(() => {
    const width = this.popupWidth();
    const style: Record<string, string> = {};
    if (width !== undefined) style["width"] = typeof width === "number" ? `${width}px` : width;
    return style;
  });

  protected readonly popoverClass = computed(() => {
    const size = this.size();
    return size === "medium"
      ? "okkly-select-popover"
      : `okkly-select-popover okkly-select-popover--${size}`;
  });

  constructor() {
    // Highlight follows the current value each time the popup opens, then
    // clears once it closes — mirrors `useSelect`'s isOpen/flatOptions effect.
    effect(() => {
      if (!this.open()) {
        this.highlightedIndex.set(-1);
        return;
      }
      const flat = this.flatOptions();
      const firstSelected = flat.findIndex((option) => this.isSelected(option));
      this.highlightedIndex.set(
        firstSelected >= 0 ? firstSelected : findNextEnabledIndex(flat, -1, 1),
      );
    });

    // Popper has no dismissal of its own; the whole field counts as "inside",
    // and the panel is portaled elsewhere in the DOM, so both are checked.
    effect((onCleanup) => {
      if (!this.open()) return;
      const onPointerDown = (event: MouseEvent) => {
        const target = event.target as Node;
        if (this.host.nativeElement.contains(target)) return;
        if (this.panel()?.nativeElement.contains(target)) return;
        this.setOpen(false);
      };
      this.document.addEventListener("mousedown", onPointerDown);
      onCleanup(() => this.document.removeEventListener("mousedown", onPointerDown));
    });
  }

  protected setOpen(open: boolean): void {
    if (this.disabled()) return;
    this.open.set(open);
  }

  /**
   * The chevron and the field's own padding live outside the trigger (Field
   * adornments), so without this they would be dead space. Clicks that
   * started on the trigger or a button (clear, a chip's ×) are left to their
   * own handlers — otherwise every one of them would toggle twice.
   */
  protected onControlClick(event: MouseEvent): void {
    if (this.disabled()) return;
    const target = event.target as HTMLElement;
    if (target.closest('button, [role="combobox"]')) return;
    this.setOpen(!this.open());
    this.triggerElement()?.nativeElement.focus();
  }

  protected onTriggerClick(): void {
    if (this.disabled()) return;
    this.setOpen(!this.open());
  }

  protected onTriggerKeydown(event: KeyboardEvent): void {
    if (this.disabled()) return;
    const { key } = event;

    if (key === "ArrowDown") {
      event.preventDefault();
      if (!this.open()) this.setOpen(true);
      else
        this.highlightedIndex.set(
          findNextEnabledIndex(this.flatOptions(), this.highlightedIndex(), 1),
        );
      return;
    }
    if (key === "ArrowUp") {
      event.preventDefault();
      if (!this.open()) this.setOpen(true);
      else
        this.highlightedIndex.set(
          findNextEnabledIndex(this.flatOptions(), this.highlightedIndex(), -1),
        );
      return;
    }
    if (key === "Enter" || key === " ") {
      event.preventDefault();
      if (!this.open()) {
        this.setOpen(true);
        return;
      }
      if (this.highlightedIndex() >= 0) this.selectOption(this.highlightedIndex());
      return;
    }
    if (key === "Escape") {
      event.preventDefault();
      this.setOpen(false);
      return;
    }
    if (key === "Home") {
      event.preventDefault();
      this.highlightedIndex.set(findNextEnabledIndex(this.flatOptions(), -1, 1));
      return;
    }
    if (key === "End") {
      event.preventDefault();
      this.highlightedIndex.set(findNextEnabledIndex(this.flatOptions(), 0, -1));
      return;
    }
    if (key.length === 1 && !event.ctrlKey && !event.metaKey && !event.altKey) {
      const now = Date.now();
      const typeahead = this.typeahead;
      const query = now - typeahead.at < 500 ? typeahead.query + key : key;
      this.typeahead.query = query;
      this.typeahead.at = now;

      if (!this.open()) this.setOpen(true);

      const needle = query.toLowerCase();
      const flat = this.flatOptions();
      const isMatch = (option: SelectOption) =>
        !option.disabled && option.label.toLowerCase().startsWith(needle);
      const after = flat.findIndex(
        (option, index) => index > this.highlightedIndex() && isMatch(option),
      );
      const nextIndex = after >= 0 ? after : flat.findIndex(isMatch);
      if (nextIndex >= 0) this.highlightedIndex.set(nextIndex);
    }
  }

  protected optionRowClass(index: number, option: SelectOption): string {
    return [
      "okkly-select__option",
      this.highlightedIndex() === index && "okkly-select__option--highlighted",
      this.isSelected(option) && "okkly-select__option--selected",
      option.disabled && "okkly-select__option--disabled",
    ]
      .filter(Boolean)
      .join(" ");
  }

  protected onOptionMouseEnter(index: number, option: SelectOption): void {
    if (!option.disabled) this.highlightedIndex.set(index);
  }

  protected onOptionClick(index: number, option: SelectOption): void {
    if (option.disabled) return;
    this.selectOption(index);
  }

  protected selectOption(index: number): void {
    const option = this.flatOptions()[index];
    if (!option || option.disabled) return;

    if (this.multiple()) {
      const current = normalizeMultipleValue(this.value());
      const exists = current.includes(option.value);
      const next = exists ? current.filter((v) => v !== option.value) : [...current, option.value];
      this.value.set(next);
      this.change.emit({ value: next, reason: exists ? "removeOption" : "selectOption", option });
      if (!this.keepOpenOnSelect()) this.setOpen(false);
      return;
    }

    this.value.set(option.value);
    this.change.emit({ value: option.value, reason: "selectOption", option });
    if (!this.keepOpenOnSelect()) {
      this.setOpen(false);
      this.triggerElement()?.nativeElement.focus();
    }
  }

  protected removeValue(option: SelectOption): void {
    if (!this.multiple()) {
      this.value.set(null);
      this.change.emit({ value: null, reason: "removeOption", option });
      return;
    }
    const next = normalizeMultipleValue(this.value()).filter((v) => v !== option.value);
    this.value.set(next);
    this.change.emit({ value: next, reason: "removeOption", option });
  }

  protected onClearClick(event: MouseEvent): void {
    event.stopPropagation();
    if (this.disableClearable() || this.disabled()) return;
    if (this.multiple()) {
      this.value.set([]);
      this.change.emit({ value: [], reason: "clear" });
    } else {
      this.value.set(null);
      this.change.emit({ value: null, reason: "clear" });
    }
  }
}
